WHENEVER SQLERROR CONTINUE;
DROP INDEX IDX_LOG_DAY_REL_1;
DROP INDEX IDX_LOG_DAY_REL_2;
DROP INDEX IDX_LOG_DAY_REL_3;
DROP INDEX IDX_LOG_DAY_REL_4;
CREATE INDEX IDX_LOG_DAY_REL_1
   ON LOG_DAY_RELEASE (REL_POI_STA);

CREATE INDEX IDX_LOG_DAY_REL_2
   ON LOG_DAY_RELEASE (REL_ALL_STA);

CREATE INDEX IDX_LOG_DAY_REL_3
   ON LOG_DAY_RELEASE (REL_POI_LOCK);

CREATE INDEX IDX_LOG_DAY_REL_4
   ON LOG_DAY_RELEASE (REL_ALL_LOCK);
COMMIT;
EXIT;