SELECT P.* FROM IX_HAMLET P,TEMP_IX_POI T WHERE P.PID=T.PID;
SELECT P.* FROM IX_HAMLET_NAME P,TEMP_IX_POI T WHERE P.PID=T.PID;
SELECT P.* FROM IX_HAMLET_NAME_TONE P WHERE P.NAME_ID IN(SELECT PH.NAME_ID FROM IX_HAMLET_NAME PH,TEMP_IX_POI T WHERE PH.PID=T.PID );
SELECT P.* FROM IX_HAMLET_FLAG P,TEMP_IX_POI T WHERE P.PID=T.PID;


