SELECT P.* FROM IX_POI P,TEMP_IX_POI T WHERE P.PID=T.PID;
SELECT P.* FROM IX_POI_NAME P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_POI_NAME_TONE P WHERE  P.NAME_ID IN (SELECT PN.NAME_ID FROM IX_POI_NAME PN,TEMP_IX_POI T WHERE PN.POI_PID=T.PID );
SELECT P.* FROM IX_POI_ADDRESS P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_POI_CONTACT P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_POI_FLAG P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_POI_ENTRYIMAGE P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_POI_ICON P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_POI_PHOTO P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_POI_AUDIO P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_POI_VIDEO P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_POI_PARENT P,TEMP_IX_POI T WHERE P.PARENT_POI_PID=T.PID;
SELECT P.* FROM IX_POI_CHILDREN P,TEMP_IX_POI T WHERE P.CHILD_POI_PID=T.PID UNION SELECT P.* FROM IX_POI_CHILDREN P WHERE  P.GROUP_ID IN(SELECT PP.GROUP_ID FROM IX_POI_PARENT PP,TEMP_IX_POI T WHERE PP.PARENT_POI_PID=T.PID );
SELECT P.* FROM IX_SAMEPOI_PART P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_SAMEPOI P WHERE group_id in (select group_id from IX_SAMEPOI_PART PS,TEMP_IX_POI T where PS.POI_PID=T.PID)
SELECT P.* FROM IX_POI_BUSINESSTIME P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_POI_INTRODUCTION P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_POI_ADVERTISEMENT P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_POI_ATTRACTION P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_POI_HOTEL P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_POI_RESTAURANT P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_POI_GASSTATION P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_POI_CHARGINGSTATION P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
SELECT P.* FROM IX_POI_CHARGINGPLOT P WHERE  P.CHARGING_ID in (select /*+ USE_HASH(PC T) */ PC.CHARGING_ID FROM IX_POI_CHARGINGSTATION PC,TEMP_IX_POI T WHERE PC.POI_PID=T.PID );

--SELECT P.* FROM IX_POI_DETAIL P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;			
--SELECT P.* FROM IX_POI_PARKING P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;
--SELECT P.* FROM IX_POI_TOURROUTE  P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;			
--SELECT P.* FROM IX_POI_EVENT P,TEMP_IX_POI T WHERE P.POI_PID=T.PID;


