INSERT INTO GLM_GRID_MAP VALUES('CMG_BUILDING','','::',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES('CMG_BUILDING_POI','','::NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES('CMG_BUILDING_NAME','','::NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES('CMG_BUILDING_3DICON','','::NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES('CMG_BUILDING_3DMODEL','','::NULL',0,'270+');