--sys库脚本
INSERT INTO CK_SUITE_RULE_MAPPING(SUITE_ID, RULE_CODE)
  VALUES('RDTMCLOCATION_CREATE_PRE', 'PERMIT_CHECK_TMC_NUM');
INSERT INTO CK_RULE(RULE_CODE, CATEGORYS, SUBCATEGORY, RULE_DESC, SEVERITY, PRE_ACCESSOR_TYPE, PRE_ACCESSOR_NAME, PRE_VARIABLES, POST_ACCESSOR_TYPE, POST_ACCESSOR_NAME, POST_VARIABLES, RULE_LOG, RULE_STATUS, RULE_MEMO)
  VALUES('PERMIT_CHECK_TMC_NUM', 'TMC', 'TMC信息', '同一个TMC位置点和同一个link最多创建两组匹配信息', 0, 'JAVA', 'com.navinfo.dataservice.engine.check.rules.PermitCheckTmcNum', NULL, NULL, NULL, NULL, '同一个TMC位置点和同一个link最多创建两组匹配信息', 'E', NULL);
--GLM54045
insert into CK_SUITE_RULE_MAPPING values('RDTMCLOCATION_UPDATE_POST','GLM54045');
INSERT INTO CK_RULE(RULE_CODE, CATEGORYS, SUBCATEGORY, RULE_DESC, SEVERITY, PRE_ACCESSOR_TYPE, PRE_ACCESSOR_NAME, PRE_VARIABLES, POST_ACCESSOR_TYPE, POST_ACCESSOR_NAME, POST_VARIABLES, RULE_LOG, RULE_STATUS, RULE_MEMO)
  VALUES('GLM54045', 'TMC', 'TMC信息', 'TMC匹配信息中的“位置方向”不能是“初始值”', 1, NULL, NULL, NULL, 'JAVA', 'com.navinfo.dataservice.engine.check.rules.GLM54045', NULL, 'TMC匹配信息中的“位置方向”不能是“初始值”', 'E', NULL);
--COM60154
insert into CK_SUITE_RULE_MAPPING values('RDTMCLOCATION_UPDATE_POST','COM60154');
INSERT INTO CK_RULE(RULE_CODE, CATEGORYS, SUBCATEGORY, RULE_DESC, SEVERITY, PRE_ACCESSOR_TYPE, PRE_ACCESSOR_NAME, PRE_VARIABLES, POST_ACCESSOR_TYPE, POST_ACCESSOR_NAME, POST_VARIABLES, RULE_LOG, RULE_STATUS, RULE_MEMO) 
	VALUES('COM60154', 'TMC', 'TMC信息', '同一个TMC点和同一个link组成的两组匹配信息中，“位置方向”不能重复', 1, '', '', '', 'JAVA', 'com.navinfo.dataservice.engine.check.rules.COM60154', '', '同一个TMC点和同一个link组成的两组匹配信息中，“位置方向”不能重复', 'E', '');
--COM60155
insert into CK_SUITE_RULE_MAPPING values('RDTMCLOCATION_UPDATE_POST','COM60155');
INSERT INTO CK_RULE(RULE_CODE, CATEGORYS, SUBCATEGORY, RULE_DESC, SEVERITY, PRE_ACCESSOR_TYPE, PRE_ACCESSOR_NAME, PRE_VARIABLES, POST_ACCESSOR_TYPE, POST_ACCESSOR_NAME, POST_VARIABLES, RULE_LOG, RULE_STATUS, RULE_MEMO) 
	VALUES('COM60155', 'TMC', 'TMC信息', '同一个TMC位置点和同一个link创建的两组匹配信息中，方向关系不能相同', 1, '', '', '', 'JAVA', 'com.navinfo.dataservice.engine.check.rules.COM60155', '', '同一个TMC位置点和同一个link创建的两组匹配信息中，方向关系不能相同', 'E', '');
