ALTER TABLE GLM_TABLES RENAME COLUMN OBJ_NAME TO OBJ_REF_TABLE;
ALTER TABLE GLM_TABLES RENAME COLUMN OBJ_PID_COL TO OBJ_REF_COL;

UPDATE GLM_TABLES SET IS_MAIN=1,OBJ_REF_TABLE='IX_POI',OBJ_REF_COL='PID' WHERE TABLE_NAME IN ('IX_POI');
--
UPDATE GLM_TABLES SET IS_MAIN=0, OBJ_REF_TABLE='IX_POI_NAME',OBJ_REF_COL='NAME_ID' WHERE TABLE_NAME IN ('IX_POI_NAME_FLAG','IX_POI_NAME_TONE');
--
UPDATE GLM_TABLES SET IS_MAIN=0, OBJ_REF_TABLE='IX_POI',OBJ_REF_COL='POI_PID' WHERE TABLE_NAME IN ('IX_POI_NAME','IX_POI_ADDRESS','IX_POI_CONTACT'
,'IX_POI_FLAG','IX_POI_ENTRYIMAGE','IX_POI_ICON','IX_POI_PHOTO','IX_POI_AUDIO','IX_POI_VIDEO'
,'IX_POI_BUILDING','IX_POI_DETAIL','IX_POI_BUSINESSTIME','IX_POI_INTRODUCTION','IX_POI_ADVERTISEMENT','IX_POI_GASSTATION','IX_POI_CHARGINGSTATION'
,'IX_POI_CHARGINGPLOT','IX_POI_CHARGINGPLOT_PH','IX_POI_PARKING','IX_POI_ATTRACTION','IX_POI_HOTEL','IX_POI_RESTAURANT','IX_POI_CARRENTAL');
--
UPDATE GLM_TABLES SET IS_MAIN=0, OBJ_REF_TABLE='IX_POI',OBJ_REF_COL='PARENT_POI_PID' WHERE TABLE_NAME IN ('IX_POI_PARENT');
UPDATE GLM_TABLES SET IS_MAIN=0, OBJ_REF_TABLE='IX_POI_PARENT',OBJ_REF_COL='GROUP_ID' WHERE TABLE_NAME IN ('IX_POI_CHILDREN');
--
UPDATE GLM_TABLES SET IS_MAIN=1,OBJ_REF_TABLE='IX_SAMEPOI',OBJ_REF_COL='GROUP_ID' WHERE TABLE_NAME IN ('IX_SAMEPOI');
UPDATE GLM_TABLES SET IS_MAIN=0,OBJ_REF_TABLE='IX_SAMEPOI',OBJ_REF_COL='GROUP_ID' WHERE TABLE_NAME IN ('IX_SAMEPOI_PART');

COMMIT;

EXIT;
