--sys库执行
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_NAME',2,0,'UNKNOWN','UNKNOWN',0,'260+');

commit;
exit;