-- glm upgrade
-- VERSION
UPDATE SYS_CONFIG SET CONF_VALUE='270+' WHERE CONF_KEY='gdb.version';
-- GLM_TABLES
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_RUNTIME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_STRAND_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_STRAND_PLATFORM',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_STRAND_SCHEDULE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_TRANSFER',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'QC_QUESTION',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_BRANCH',2,0,'RD_BRANCH','BRANCH_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_BRANCH_DETAIL',2,0,'RD_BRANCH','BRANCH_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_BRANCH_NAME',2,0,'RD_BRANCH','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_BRANCH_NAME_TONE',2,0,'RD_BRANCH','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_BRANCH_REALIMAGE',2,0,'RD_BRANCH','BRANCH_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_BRANCH_SCHEMATIC',2,0,'RD_BRANCH','BRANCH_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_BRANCH_VIA',2,0,'RD_BRANCH','BRANCH_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_CHAIN',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_CHAIN_LINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_CHAIN_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_CROSS',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_CROSSWALK',2,0,'RD_CROSSWALK','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_CROSSWALK_INFO',2,0,'RD_CROSSWALK','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_CROSSWALK_NODE',2,0,'RD_CROSSWALK','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_CROSS_LINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_CROSS_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_CROSS_NODE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_DIRECTROUTE',2,0,'RD_DIRECTROUTE','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_DIRECTROUTE_VIA',2,0,'RD_DIRECTROUTE','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_ELECEYE_PAIR',2,0,'RD_ELECEYE_PAIR','GROUP_ID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_ELECTRONICEYE',2,0,'RD_ELECTRONICEYE','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_ELECEYE_PART',2,0,'RD_ELECEYE_PAIR','GROUP_ID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_GATE',2,0,'RD_GATE','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_GATE_CONDITION',2,0,'RD_GATE','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_GSC',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_GSC_LINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_HGWG_LIMIT',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_INTER',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_INTER_LINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_INTER_NODE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LANE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LANE_CONDITION',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LANE_CONNEXITY',2,0,'RD_LANE_CONNEXITY','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LANE_TOPOLOGY',2,0,'RD_LANE_CONNEXITY','CONNEXITY_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LANE_TOPO_DETAIL',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LANE_TOPO_VIA',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LANE_VIA',2,0,'RD_LANE_CONNEXITY','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LINK_ADDRESS',2,0,'RD_LINK','LINK_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LINK_FORM',2,0,'RD_LINK','LINK_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LINK_INT_RTIC',2,0,'RD_LINK','LINK_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LINK_LIMIT',2,0,'RD_LINK','LINK_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LINK_LIMIT_TRUCK',2,0,'RD_LINK','LINK_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LINK_NAME',2,0,'RD_LINK','LINK_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LINK_PARAM_ADAS',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LINK_RTIC',2,0,'RD_LINK','LINK_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LINK_SIDEWALK',2,0,'RD_LINK','LINK_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LINK_SPEEDLIMIT',2,0,'RD_LINK','LINK_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LINK_WALKSTAIR',2,0,'RD_LINK','LINK_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LINK_WARNING',2,0,'RD_LINK_WARNING','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LINK_ZONE',2,0,'RD_LINK','LINK_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_MAINSIDE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_MAINSIDE_LINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_MILEAGEPILE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_MULTIDIGITIZED',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_MULTIDIGITIZED_LINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_NATGUD_JUN',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_NATGUD_JUN_DETAIL',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_NATGUD_JUN_VIA',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_NODE_FORM',2,0,'RD_NODE','NODE_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_NODE_MESH',2,0,'RD_NODE','NODE_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_NODE_NAME',2,0,'RD_NODE','NODE_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_OBJECT',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_OBJECT_INTER',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_OBJECT_LINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_OBJECT_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_OBJECT_NODE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_ROAD',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_OBJECT_ROAD',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_RESTRICTION',2,0,'RD_RESTRICTION','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_RESTRICTION_DETAIL',2,0,'RD_RESTRICTION','RESTRIC_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_RESTRICTION_CONDITION',2,0,'RD_RESTRICTION','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_RESTRICTION_VIA',2,0,'RD_RESTRICTION','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_ROAD_LINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_SAMELINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_SAMELINK_PART',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_SAMENODE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_SAMENODE_PART',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_SE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_SERIESBRANCH',2,0,'RD_BRANCH','BRANCH_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_SIGNASREAL',2,0,'RD_BRANCH','BRANCH_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_SIGNBOARD',2,0,'RD_BRANCH','BRANCH_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_SIGNBOARD_NAME',2,0,'RD_BRANCH','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_SIGNBOARD_NAME_TONE',2,0,'RD_BRANCH','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_SIGNPOST',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_SIGNPOST_LINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_SIGNPOST_PHOTO',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_SLOPE',2,0,'RD_SLOPE','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_SLOPE_VIA',2,0,'RD_SLOPE','SLOPE_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_SPEEDBUMP',2,0,'RD_SPEEDBUMP','BUMP_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_SPEEDLIMIT',2,0,'RD_SPEEDLIMIT','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_TMCLOCATION',2,0,'RD_TMCLOCATION','GROUP_ID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_TMCLOCATION_LINK',2,0,'RD_TMCLOCATION','GROUP_ID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_TOLLGATE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_TOLLGATE_COST',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_TOLLGATE_FEE',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_TOLLGATE_MAPPING',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_TOLLGATE_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_TOLLGATE_PASSAGE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_TRAFFICSIGNAL',2,0,'RD_TRAFFICSIGNAL','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_VARIABLE_SPEED',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_VARIABLE_SPEED_VIA',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_VIRCONNECT',2,0,'RD_VIRCONNECT','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_VIRCONNECT_NAME',2,0,'RD_VIRCONNECT','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_VIRCONNECT_TRANSIT',2,0,'RD_VIRCONNECT','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_VOICEGUIDE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_VOICEGUIDE_DETAIL',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_VOICEGUIDE_VIA',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_WARNINGINFO',2,0,'RD_WARNINGINFO','PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RI_FEATURE',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RI_OPERATION',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RW_FEATURE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RW_FEATURE_20W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RW_NODE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RW_LINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RW_NODE_20W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RW_LINK_20W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RW_LINK_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RW_LINK_NAME_20W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RW_NODE_MESH',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RW_NODE_MESH_20W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'TB_ABSTRACT_INFO',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'TB_INTELLIGENCE',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'WL_CHECKCOUNT',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'WL_CHECKLOG',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ZONE_FACE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ZONE_NODE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ZONE_LINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ZONE_FACE_TOPO',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ZONE_LINK_KIND',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ZONE_LINK_MESH',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ZONE_NODE_MESH',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CMG_BUILDFACE_TENANT',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CMG_BUILDNODE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CMG_BUILDLINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CMG_BUILDFACE_TOPO',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CMG_BUILDING_3DICON',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CMG_BUILDING_3DMODEL',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CMG_BUILDING_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CMG_BUILDING_POI',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CMG_BUILDLINK_MESH',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CMG_BUILDNODE_MESH',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CM_BUILDING',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CM_BUILDFACE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CM_BUILDNODE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CM_BUILDLINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CM_BUILDFACE_TOPO',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CM_BUILDLINK_MESH',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CM_BUILDNODE_MESH',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'DEM_GRID',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'DEM_ELEVATION',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'DTM_INFO',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'EF_3DMAP',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'EF_IMAGE',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'EF_LINEMAP',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'HWY_JUNCTION',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'HWY_JCT',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'HWY_JCT_LINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'HWY_JUNCTION_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'HWY_SAPA',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'HW_ESTAB',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'HW_ESTAB_MAIN',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'HW_ESTAB_CONTAIN',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'HW_ESTAB_JCT',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'HW_ESTAB_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'HW_ESTAB_ROUTE_POS',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'HW_ESTAB_SA',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'HW_POSITION',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'HW_ROUTE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IDB_COUNTRY_INFO',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IDB_DIFF_INFO',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IDB_REGION_INFO',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_ANNOTATION',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_ANNOTATION_100W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_ANNOTATION_FLAG',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_ANNOTATION_FLAG_100W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_ANNOTATION_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_ANNOTATION_NAME_100W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_CROSSPOINT',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_HAMLET',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_HAMLET_FLAG',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_HAMLET_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_HAMLET_NAME_TONE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_IC',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_NATGUD',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_NATGUD_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POINTADDRESS',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POINTADDRESS_PARENT',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POINTADDRESS_CHILDREN',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POINTADDRESS_FLAG',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POINTADDRESS_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POINTADDRESS_NAME_TONE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_ADDRESS',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_ADVERTISEMENT',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_ATTRACTION',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_AUDIO',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_BUILDING',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_BUSINESSTIME',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_CARRENTAL',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_CHARGINGPLOT',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_CHARGINGPLOT_PH',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_CHARGINGSTATION',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_PARENT',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_CHILDREN',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_CONTACT',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_DETAIL',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_ENTRYIMAGE',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_EVENT',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_FLAG',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_GASSTATION',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_HOTEL',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_ICON',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_INTRODUCTION',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_NAME',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_NAME_FLAG',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_NAME_TONE',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_PARKING',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_PHOTO',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_RESTAURANT',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_TOURROUTE',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POI_VIDEO',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_POSTCODE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_ROADNAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_SAMEPOI',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_SAMEPOI_PART',1,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'IX_TOLLGATE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_FACE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_FACE_100W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_FACE_20W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_FACE_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_FACE_NAME_100W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_FACE_NAME_20W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_FACE_TOP',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_FACE_NAME_TOP',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_NODE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_LINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_FACE_TOPO',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_NODE_100W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_LINK_100W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_FACE_TOPO_100W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_NODE_20W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_LINK_20W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_FACE_TOPO_20W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_NODE_TOP',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_LINK_TOP',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_FACE_TOPO_TOP',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_FEATURE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_FEATURE_100W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_FEATURE_20W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_FEATURE_TOP',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_LINK_KIND',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_LINK_KIND_100W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_LINK_KIND_20W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_LINK_KIND_TOP',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_LINK_MESH',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_LINK_MESH_100W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_LINK_MESH_20W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_LINK_MESH_TOP',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_NODE_MESH',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_NODE_MESH_100W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_NODE_MESH_20W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LC_NODE_MESH_TOP',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LU_FACE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LU_FACE_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LU_NODE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LU_LINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LU_FACE_TOPO',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LU_FEATURE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LU_LINK_KIND',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LU_LINK_MESH',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'LU_NODE_MESH',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'M_MESH_TYPE',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'M_PARAMETER',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'M_UPDATE_PARAMETER',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'NI_VAL_EXCEPTION',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ACH_GDB_INFO',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_NODE',2,0,'RD_NODE','NODE_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_LINK',2,0,'RD_LINK','LINK_PID',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ADAS_ITPLINK_GEOMETRY',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ADAS_NODE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ADAS_LINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ADAS_LINK_GEOMETRY',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ADAS_NODE_INFO',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ADAS_NODE_MESH',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ADAS_RDLINK_GEOMETRY_DTM',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ADAS_RDNODE_INFO_DTM',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ADAS_RDNODE_SLOPE_DTM',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'ADAS_SLOPE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AD_ADMIN',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AD_ADMIN_DETAIL',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AD_ADMIN_GROUP',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AD_ADMIN_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AD_ADMIN_NAME_TONE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AD_ADMIN_PART',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AD_FACE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AD_NODE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AD_LINK',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AD_FACE_TOPO',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AD_NODE_100W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AD_LINK_100W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AD_LINK_MESH',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AD_LINK_MESH_100W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AD_NODE_MESH',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AD_NODE_MESH_100W',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_ADAS_MARK',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_ADAS_GPSRECORD',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_ADAS_GPSTRACK',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_AUDIO',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_COMMUNICATION',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_DATA_STATISTICS',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_MARK',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_DRAFT',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_GPSRECORD',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_GPSTRACK_GROUP',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_GPSTRACK',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_GPSTRACK_GROUP_VIDEO',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_GPSTRACK_PHOTO',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_ANNOTATION',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_ANNOTATION_NAME',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POINTADDRESS',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POINTADDRESS_CHILDREN',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POINTADDRESS_FLAG',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POINTADDRESS_NAME',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POINTADDRESS_PARENT',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_ADDRESS',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_BUILDING',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_CHARGINGSTATION',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_CHARGINGPLOT',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_CHILDREN',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_CONTACT',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_FLAG',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_GASSTATION',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_HOTEL',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_NAME',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_NAME_FLAG',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_RP00',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_NAME_RP00',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_NOKIA',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_PARENT',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_PARKING',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_PHOTO',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_POI_RESTAURANT',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_SAMEPOI',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_IX_SAMEPOI_PART',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_LOG_STATISTICS',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_MARK_AUDIO',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_MARK_PHOTO',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_MARK_VIDEO',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PHOTO',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_COMPANY',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_POI',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_ETA_ACCESS',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_LINE',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_ETA_LINE',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_ETA_STOP',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_LINE_NAME',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_PLATFORM',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_PLATFORM_ACCESS',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_PLATFORM_NAME',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_POI_PARENT',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_POI_CHILDREN',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_POI_NAME',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_STRAND',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_STRAND_NAME',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_STRAND_PLATFORM',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_SYSTEM',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_PT_TRANSFER',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_RECEIVE',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_SERIESPHOTO',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_SPECIALCASE',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_SPECIALCASE_IMAGE',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_TASK_INFO',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_TOPOIMAGE',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_VIDEO',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_WHITEBOARD',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'AU_WHITEBOARD_PARAMETER',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'BI_PERSON',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'BI_ROLE',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'BI_PERSON_ROLE',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'BI_POWER',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'BI_ROLE_POWER',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'BI_TASK',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CK_EXCEPTION',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CK_RULE',2,0,'UNKNOWN','UNKNOWN',0,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CMG_BUILDING',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'CMG_BUILDFACE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_COMPANY',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_POI',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_ETA_ACCESS',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_ETA_COMPANY',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_LINE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_ETA_LINE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_ETA_STOP',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_SYSTEM',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_ETA_SYSTEM',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_LINE_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_PLATFORM',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_PLATFORM_ACCESS',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_PLATFORM_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_POI_PARENT',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_POI_CHILDREN',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_POI_FLAG',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_POI_NAME',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_POI_NAME_TONE',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'PT_STRAND',2,0,'UNKNOWN','UNKNOWN',1,'270+');
INSERT INTO GLM_TABLES(TABLE_ID,TABLE_NAME,FEATURE_TYPE,IS_MAIN,OBJ_NAME,OBJ_PID_COL,EDITABLE,GDB_VERSION) VALUES (GLM_TABLE_SEQ.NEXTVAL,'RD_NAME',2,0,'UNKNOWN','UNKNOWN',0,'270+');

COMMIT;

-- GLM_GRID_MAP
--RD_NODE
INSERT INTO GLM_GRID_MAP VALUES ('RD_NODE','','',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_NODE_FORM','NODE_PID','RD_NODE:NODE_PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_NODE_MESH','NODE_PID','RD_NODE:NODE_PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_NODE_NAME','NODE_PID','RD_NODE:NODE_PID:NULL',0,'270+');
--RD_LINK
INSERT INTO GLM_GRID_MAP VALUES ('RD_LINK','','',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_LINK_FORM','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_LINK_LIMIT','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_LINK_LIMIT_TRUCK','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_LINK_SPEEDLIMIT','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_LINK_SIDEWALK','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_LINK_WALKSTAIR','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_LINK_RTIC','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_LINK_INT_RTIC','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_LINK_ZONE','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_LINK_NAME','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_LINK_ADDRESS','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
--RD_RESTRICTION
INSERT INTO GLM_GRID_MAP VALUES ('RD_RESTRICTION','IN_LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_RESTRICTION_DETAIL','OUT_LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_RESTRICTION_CONDITION','DETAIL_ID','RD_RESTRICTION_DETAIL:DETAIL_ID:OUT_LINK_PID,RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_RESTRICTION_VIA','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
--RD_SPEEDLIMIT
INSERT INTO GLM_GRID_MAP VALUES ('RD_SPEEDLIMIT','','',1,'270+');
--RD_CROSS
INSERT INTO GLM_GRID_MAP VALUES ('RD_CROSS','','',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_CROSS_LINK','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_CROSS_NAME','','',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_CROSS_NODE','NODE_PID','RD_NODE:NODE_PID:NULL',0,'270+');
--RD_BRANCH
INSERT INTO GLM_GRID_MAP VALUES ('RD_BRANCH','IN_LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_BRANCH_DETAIL','BRANCH_PID','RD_BRANCH:BRANCH_PID:OUT_LINK_PID,RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_BRANCH_NAME','DETAIL_ID','RD_BRANCH_DETAIL:DETAIL_ID:BRANCH_PID,RD_BRANCH:BRANCH_PID:OUT_LINK_PID,RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_BRANCH_VIA','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_BRANCH_REALIMAGE','BRANCH_PID','RD_BRANCH:BRANCH_PID:OUT_LINK_PID,RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_BRANCH_SCHEMATIC','BRANCH_PID','RD_BRANCH:BRANCH_PID:OUT_LINK_PID,RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_SIGNBOARD','BRANCH_PID','RD_BRANCH:BRANCH_PID:OUT_LINK_PID,RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_SIGNBOARD_NAME','SIGNBOARD_ID','RD_SIGNBOARD:SIGNBOARD_ID:BRANCH_PID,RD_BRANCH:BRANCH_PID:OUT_LINK_PID,RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_SIGNASREAL','BRANCH_PID','RD_BRANCH:BRANCH_PID:OUT_LINK_PID,RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_SERIESBRANCH','BRANCH_PID','RD_BRANCH:BRANCH_PID:OUT_LINK_PID,RD_LINK:LINK_PID:NULL',1,'270+');
-- RD_MILEAGEPILE
INSERT INTO GLM_GRID_MAP VALUES('RD_MILEAGEPILE','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
-- RD_LANE
INSERT INTO GLM_GRID_MAP VALUES ('RD_LANE','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_LANE_CONDITION','LANE_PID','RD_LANE:LANE_PID:LINK_PID,RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_LANE_TOPO_DETAIL','IN_LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_LANE_TOPO_VIA','VIA_LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
--RD_LANE_CONNEXITY
INSERT INTO GLM_GRID_MAP VALUES ('RD_LANE_CONNEXITY','IN_LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_LANE_TOPOLOGY','OUT_LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_LANE_VIA','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
--RD_GSC
INSERT INTO GLM_GRID_MAP VALUES ('RD_GSC','','',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_GSC_LINK','PID','RD_GSC:PID:NULL',0,'270+');
-- RD_GATE
INSERT INTO GLM_GRID_MAP VALUES ('RD_GATE','NODE_PID','RD_NODE:NODE_PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_GATE_CONDITION','PID','RD_GATE:PID:NODE_PID,RD_NODE:NODE_PID:NULL',0,'270+');
--AD_ADMIN
INSERT INTO GLM_GRID_MAP VALUES ('AD_ADMIN','','',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('AD_ADMIN_NAME','REGION_ID','AD_ADMIN:REGION_ID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('AD_ADMIN_GROUP','REGION_ID_UP','AD_ADMIN:REGION_ID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('AD_ADMIN_PART','REGION_ID_DOWN','AD_ADMIN:REGION_ID:NULL',1,'270+');
--AD_FACE
INSERT INTO GLM_GRID_MAP VALUES ('AD_FACE','','',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('AD_FACE_TOPO','LINK_PID','AD_LINK:LINK_PID:NULL',0,'270+');
--AD_LINK
INSERT INTO GLM_GRID_MAP VALUES ('AD_LINK','','',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('AD_LINK_MESH','LINK_PID','AD_LINK:LINK_PID:NULL',0,'270+');
--AD_NODE
INSERT INTO GLM_GRID_MAP VALUES ('AD_NODE','','',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('AD_NODE_MESH','NODE_PID','AD_NODE:NODE_PID:NULL',0,'270+');
--CK_EXCEPTION
INSERT INTO GLM_GRID_MAP VALUES ('CK_EXCEPTION','','',0,'270+');
--ZONE_FACE
INSERT INTO GLM_GRID_MAP VALUES ('ZONE_FACE','','',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('ZONE_FACE_TOPO','LINK_PID','ZONE_LINK:LINK_PID:NULL',0,'270+');
--ZONE_LINK
INSERT INTO GLM_GRID_MAP VALUES ('ZONE_LINK','','',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('ZONE_LINK_MESH','LINK_PID','ZONE_LINK:LINK_PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('ZONE_LINK_KIND','LINK_PID','ZONE_LINK:LINK_PID:NULL',0,'270+');
--ZONE_NODE
INSERT INTO GLM_GRID_MAP VALUES ('ZONE_NODE','','',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('ZONE_NODE_MESH','NODE_PID','ZONE_NODE:NODE_PID:NULL',0,'270+');
--RW_LINK
INSERT INTO GLM_GRID_MAP VALUES ('RW_LINK','','',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RW_LINK_NAME','LINK_PID','RW_LINK:LINK_PID:NULL',0,'270+');
--RW_NODE
INSERT INTO GLM_GRID_MAP VALUES ('RW_NODE','','',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RW_NODE_MESH','NODE_PID','RW_NODE:NODE_PID:NULL',0,'270+');
--IX_POI
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI','','',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_NAME','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_NAME_FLAG','NAME_ID','IX_POI_NAME:NAME_ID:POI_PID,IX_POI:PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_NAME_TONE','NAME_ID','IX_POI_NAME:NAME_ID:POI_PID,IX_POI:PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_ADDRESS','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_CONTACT','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_FLAG','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_ENTRYIMAGE','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_ICON','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_PHOTO','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_AUDIO','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_VIDEO','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_PARENT','PARENT_POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_CHILDREN','CHILD_POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_BUILDING','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_DETAIL','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_BUSINESSTIME','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_INTRODUCTION','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_ADVERTISEMENT','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_GASSTATION','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_CHARGINGSTATION','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_CHARGINGPLOT','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_CHARGINGPLOT_PH','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_PARKING','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_ATTRACTION','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_HOTEL','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_RESTAURANT','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_TOURROUTE','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_EVENT','POI_PID','IX_POI:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('IX_POI_CARRENTAL','POI_PID','IX_POI:PID:NULL',0,'270+');
-- CMG_BUILD
INSERT INTO GLM_GRID_MAP VALUES ('CMG_BUILDNODE',NULL,NULL,0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('CMG_BUILDNODE_MESH','NODE_PID','CMG_BUILDNODE:NODE_PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('CMG_BUILDLINK',NULL,NULL,0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('CMG_BUILDLINK_MESH','LINK_PID','CMG_BUILDLINK:LINK_PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('CMG_BUILDFACE',NULL,NULL,1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('CMG_BUILDFACE_TENANT','FACE_PID','CMG_BUILDFACE:FACE_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('CMG_BUILDFACE_TOPO','LINK_PID','CMG_BUILDLINK:LINK_PID:NULL',0,'270+');
-- LC
INSERT INTO GLM_GRID_MAP VALUES ('LC_FACE',NULL,NULL,1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('LC_FACE_NAME','FACE_PID','LC_FACE:FACE_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('LC_FACE_TOPO','LINK_PID','LC_LINK:LINK_PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('LC_LINK',NULL,NULL,0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('LC_LINK_KIND','LINK_PID','LC_LINK:LINK_PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('LC_LINK_MESH','LINK_PID','LC_LINK:LINK_PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('LC_NODE',NULL,NULL,0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('LC_NODE_MESH','NODE_PID','LC_NODE:NODE_PID:NULL',0,'270+');
-- DELETE FROM GLM_GRID_MAP WHERE TABLE_NAME = 'LC_FEATURE'
INSERT INTO GLM_GRID_MAP VALUES ('LC_FEATURE','FEATURE_PID','LC_FACE:FEATURE_PID:NULL',1,'270+');
-- HW
-- DELETE FROM GLM_GRID_MAP WHERE TABLE_NAME = 'HW_ESTAB_JCT'
INSERT INTO GLM_GRID_MAP VALUES ('HW_ESTAB_JCT','JCTLINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('HW_POSITION','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
-- RD_DIRECTROUTE
INSERT INTO GLM_GRID_MAP VALUES ('RD_DIRECTROUTE','IN_LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_DIRECTROUTE_VIA','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
-- CRF
INSERT INTO GLM_GRID_MAP VALUES ('RD_INTER','PID','RD_INTER_LINK:PID:LINK_PID,RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_INTER_LINK','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_INTER_NODE','NODE_PID','RD_NODE:NODE_PID:NULL',0,'270+');

INSERT INTO GLM_GRID_MAP VALUES ('RD_ROAD','PID','RD_ROAD_LINK:PID:LINK_PID,RD_LINK:LINK_PID:NULL',1,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_ROAD_LINK','LINK_PID','RD_LINK:LINK_PID:NULL',1,'270+');

INSERT INTO GLM_GRID_MAP VALUES ('RD_OBJECT',NULL,NULL,0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_OBJECT_NAME','PID','RD_OBJECT:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_OBJECT_INTER','PID','RD_OBJECT:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_OBJECT_ROAD','PID','RD_OBJECT:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_OBJECT_LINK','PID','RD_OBJECT:PID:NULL',0,'270+');
INSERT INTO GLM_GRID_MAP VALUES ('RD_OBJECT_NODE','PID','RD_OBJECT:PID:NULL',0,'270+');

-- IX_ANNOTATION
INSERT INTO GLM_GRID_MAP VALUES ('IX_ANNOTATION','','',1,'270+');

-- IX_SAMEPOI
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('IX_SAMEPOI', 'GROUP_ID', 'IX_SAMEPOI_PART:GROUP_ID:POI_PID,IX_POI:PID:NULL', 1, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('IX_SAMEPOI_PART', 'POI_PID', 'IX_POI:PID:NULL', 1, '270+');
-- LU
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('LU_FACE', NULL, NULL, 1, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('LU_FACE_NAME', 'FACE_PID', 'LU_FACE:FACE_PID:NULL', 0, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('LU_FACE_TOPO', 'LINK_PID', 'LU_LINK:LINK_PID:NULL', 0, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('LU_LINK', NULL, NULL, 0, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('LU_LINK_KIND', 'LINK_PID', 'LU_LINK:LINK_PID:NULL', 0, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('LU_LINK_MESH', 'LINK_PID', 'LU_LINK:LINK_PID:NULL', 0, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('LU_NODE', 'NODE_PID', 'LU_NODE:NODE_PID:NULL', 0, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('LU_NODE_MESH', 'NODE_PID', 'LU_NODE:NODE_PID:NULL', 0, '270+');
-- RD_ELECTRONICEYE
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_ELECEYE_PAIR', 'GROUP_ID', 'RD_ELECEYE_PART:GROUP_ID:ELECEYE_PID,RD_ELECTRONICEYE:PID:NULL', 0, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_ELECEYE_PART', 'ELECEYE_PID', 'RD_ELECTRONICEYE:PID:NULL', 0, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_ELECTRONICEYE', NULL, NULL, 0, '270+');
-- RD_SAMELINK
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_SAMELINK', 'GROUP_ID', 'RD_SAMELINK_PART:GROUP_ID:LINK_PID,RD_LINK:LINK_PID:NULL', 0, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_SAMELINK_PART', 'LINK_PID', 'RD_LINK:LINK_PID:NULL', 0, '270+');
-- RD_SAMENODE
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_SAMENODE', 'GROUP_ID', 'RD_SAMENODE_PART:GROUP_ID:NODE_PID,RD_NODE:NODE_PID:NULL', 0, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_SAMENODE_PART', 'NODE_PID', 'RD_NODE:NODE_PID:NULL', 0, '270+');
-- RD_SE
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_SE', 'NODE_PID', 'RD_NODE:NODE_PID:NULL', 0, '270+');
-- RD_SLOPE
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_SLOPE', 'NODE_PID', 'RD_NODE:NODE_PID:NULL', 0, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_SLOPE_VIA', 'LINK_PID', 'RD_LINK:LINK_PID:NULL', 0, '270+');
-- RD_SPEEDBUMP
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_SPEEDBUMP', 'NODE_PID', 'RD_NODE:NODE_PID:NULL', 0, '270+');
-- RD_TOLLGATE
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_TOLLGATE', 'NODE_PID', 'RD_NODE:NODE_PID:NULL', 0, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_TOLLGATEP_ASSAGE', 'PID', 'RD_TOLLGATE:PID:NODE_PID,RD_NODE:NODE_PID:NULL', 0, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_TOLLGATE_NAME', 'PID', 'RD_TOLLGATE:PID:NODE_PID,RD_NODE:NODE_PID:NULL', 0, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_TOLLGATE_PASSAGE', 'PID', 'RD_TOLLGATE:PID:NODE_PID,RD_NODE:NODE_PID:NULL', 0, '270+');
-- RD_TRAFFICSIGNAL
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_TRAFFICSIGNAL', NULL, NULL, 0, '270+');
-- RD_VARIABLE_SPEED
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_VARIABLE_SPEED', 'IN_LINK_PID', 'RD_LINK:LINK_PID:NULL', 1, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_VARIABLE_SPEED_VIA', 'LINK_PID', 'RD_LINK:LINK_PID:NULL', 1, '270+');
-- RD_VOICEGUIDE
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_VOICEGUIDE', 'IN_LINK_PID', 'RD_LINK:LINK_PID:NULL', 1, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_VOICEGUIDE_DETAIL', 'OUT_LINK_PID', 'RD_LINK:LINK_PID:NULL', 1, '270+');
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_VOICEGUIDE_VIA', 'LINK_PID', 'RD_LINK:LINK_PID:NULL', 1, '270+');
-- RD_WARNINGINFO
INSERT INTO glm_grid_map(TABLE_NAME, REF_COL_NAME, REF_INFO, SINGLE_MESH, GDB_VERSION)
  VALUES('RD_WARNINGINFO', 'NODE_PID', 'RD_NODE:NODE_PID:NULL', 0, '270+');

COMMIT;

EXIT;