-- DROP TABLE GLOBAL_ID_USAGE;
CREATE TABLE GLOBAL_ID_USAGE(
TABLE_NAME VARCHAR(30) NOT NULL,
START_ID NUMBER(10) NOT NULL,
SEG_SIZE NUMBER(10) NOT NULL,
CONSTRAINT PK_GLOBAL_ID_USAGE PRIMARY KEY (TABLE_NAME,START_ID)
);
CREATE INDEX IX_PID_USAGE_01 ON GLOBAL_ID_USAGE(TABLE_NAME);

-- DROP TABLE GLOBAL_ID_LOG;
CREATE TABLE GLOBAL_ID_LOG(
  TABLE_NAME VARCHAR(30),
  START_ID NUMBER(10),
  SEG_SIZE NUMBER(10),
  OPERATE_TYPE INT,
  MEMO VARCHAR2(128)
);

CREATE OR REPLACE PACKAGE GLOBAL_ID_MAN IS
  FUNCTION GET(P_TABLE_NAME VARCHAR2,P_COUNT NUMBER)RETURN NUMBER;
  /**
  * 独立事务,记录日志
  */
  FUNCTION GET_STANDALONE(P_TABLE_NAME VARCHAR2,P_COUNT NUMBER)RETURN NUMBER;
  
  FUNCTION GIVEBACK(P_TABLE_NAME VARCHAR2,P_START_ID NUMBER,P_COUNT NUMBER)RETURN NUMBER;
END GLOBAL_ID_MAN;
/
CREATE OR REPLACE PACKAGE BODY GLOBAL_ID_MAN IS
  FUNCTION GET(P_TABLE_NAME VARCHAR2,P_COUNT NUMBER)RETURN NUMBER 
  IS
    V_START_ID NUMBER;
  BEGIN
    SELECT T.START_ID INTO V_START_ID FROM (SELECT START_ID FROM GLOBAL_ID_USAGE WHERE TABLE_NAME=P_TABLE_NAME AND SEG_SIZE>=P_COUNT ORDER BY DBMS_RANDOM.value) T WHERE ROWNUM=1;
    UPDATE GLOBAL_ID_USAGE SET START_ID=START_ID+P_COUNT,SEG_SIZE=SEG_SIZE-P_COUNT WHERE TABLE_NAME=P_TABLE_NAME AND START_ID=V_START_ID;
    IF SQL%ROWCOUNT = 1 THEN
      RETURN V_START_ID;
    ELSE
      RETURN 0;
    END IF;
  END;
  FUNCTION GET_STANDALONE(P_TABLE_NAME VARCHAR2,P_COUNT NUMBER)RETURN NUMBER 
  IS PRAGMA AUTONOMOUS_TRANSACTION;
    V_START_ID NUMBER;
  BEGIN
    SELECT T.START_ID INTO V_START_ID FROM (SELECT START_ID FROM GLOBAL_ID_USAGE WHERE TABLE_NAME=P_TABLE_NAME AND SEG_SIZE>=P_COUNT ORDER BY DBMS_RANDOM.value) T WHERE ROWNUM=1;
    UPDATE GLOBAL_ID_USAGE SET START_ID=START_ID+P_COUNT,SEG_SIZE=SEG_SIZE-P_COUNT WHERE TABLE_NAME=P_TABLE_NAME AND START_ID=V_START_ID;
    IF SQL%ROWCOUNT = 1 THEN
      INSERT INTO GLOBAL_ID_LOG (TABLE_NAME,START_ID,SEG_SIZE,OPERATE_TYPE,MEMO) VALUES (P_TABLE_NAME,V_START_ID,P_COUNT,1,'temp');
      COMMIT;
      RETURN V_START_ID;
    ELSE
      ROLLBACK;
      RETURN GET(P_TABLE_NAME,P_COUNT);
    END IF;
  END;
  FUNCTION GIVEBACK(P_TABLE_NAME VARCHAR2,P_START_ID NUMBER,P_COUNT NUMBER)RETURN NUMBER
  IS
    V_RESULT NUMBER:=1;
  BEGIN
    RETURN V_RESULT;
  END;
END GLOBAL_ID_MAN;
/
EXIT;
