-- INIT
DECLARE CURSOR T_CURSOR IS SELECT COLUMN_VALUE TN FROM TABLE(VARCHAR_TO_TABLE('RD_LINK,RD_NODE,RD_RESTRICTION,RD_RESTRICTION_DETAIL,RD_NODE_NAME,RD_SPEEDLIMIT,RD_CROSS,RD_CROSS_NAME,RD_BRANCH,RD_BRANCH_DETAIL,RD_BRANCH_NAME,RD_SIGNASREAL,RD_BRANCH_SCHEMATIC,RD_SIGNBOARD,RD_SIGNBOARD_NAME,CK_EXCEPTION,RD_TRAFFICSIGNAL,RD_DIRECTROUTE,AD_ADMIN,AD_ADMIN_NAME,AD_NODE,RW_NODE,RW_LINK,AD_LINK,AD_FACE,RD_VARIABLE_SPEED,RTIC_CODE,AD_ADMIN_GROUP,RD_GSC,IX_POI,IX_POI_NAME,IX_POI_ADDRESS,IX_POI_PARENT,IX_POI_GASSTATION,IX_POI_PARKING,IX_POI_HOTEL,IX_POI_FOOD,IX_POI_ICON,IX_POI_ATTRACTION,IX_POI_RESTAURANT,ZONE_NODE,ZONE_LINK,RD_LANE,RD_LANE_TOPOLOGY,RD_LANE_CONNEXITY,ZONE_FACE,RD_NAME,LU_NODE,LU_LINK,LU_FACE,LU_FACE_NAME,RD_ELECTRONICEYE,RD_ELECEYE_PAIR,RD_WARNINGINFO,RD_SLOPE,RD_GATE,LC_NODE,LC_LINK,LC_FACE,LC_FACE_NAME,RD_SE,RD_INTER,RD_OBJECT,RD_SPEEDBUMP,RD_SAMENODE,RD_SAMELINK,RD_TOLLGATE,RD_TOLLGATE_NAME,RD_VOICEGUIDE,RD_VOICEGUIDE_DETAIL,IX_SAMEPOI'));
BEGIN
  FOR REC IN T_CURSOR LOOP
    FOR I IN 1..10 LOOP
	  INSERT INTO GLOBAL_ID_USAGE(TABLE_NAME,START_ID,SEG_SIZE)VALUES(REC.TN,&1+(I-1)*1000000,1000000);
	END LOOP;
	INSERT INTO GLOBAL_ID_USAGE(TABLE_NAME,START_ID,SEG_SIZE)VALUES(REC.TN,&1+10000000,10000000);
	INSERT INTO GLOBAL_ID_USAGE(TABLE_NAME,START_ID,SEG_SIZE)VALUES(REC.TN,&1+20000000,80000000);
  END LOOP;
  COMMIT;
END;
/
EXIT;