WHENEVER SQLERROR CONTINUE;
MERGE INTO SYS_CONFIG S
USING (SELECT 'pid.connection.string' CK FROM DUAL) T ON (S.CONF_KEY=T.CK)
WHEN MATCHED THEN
  UPDATE SET CONF_VALUE=CONF_VALUE||';ORACLE,&1,&2,&3,&4,&5'
WHEN NOT MATCHED THEN
  INSERT(CONF_ID,CONF_KEY,CONF_VALUE,CONF_DESC,APP_TYPE) VALUES (SYS_CONFIG_SEQ.NEXTVAL,'pid.connection.string','ORACLE,&1,&2,&3,&4,&5','pid servers','default');
COMMIT;
EXIT;