package com.navinfo.dataservice.FosEngine.edit.model;

/**
 * 对象类型
 */
public enum ObjType {

	RDLINK, RDNODE, RDRESTRICTION, RDLANECONNEXITY, RDLINKFORM, RDLINKLIMIT, RDLINKNAME, RDRESTRICTIONVIA, RDRESTRICTIONDETAIL, RDRESTRICTIONCONDITION, RDNODEFORM, RDNODENAME, RDNODEMESH, RDCROSS, RDCROSSLINK, RDCROSSNODE, RDCROSSNAME,RDLINKLIMITTRUNK,RDLINKSPEEDLIMIT,RDLINKSIDEWALK,RDLINKWALKSTAIR,RDLINKRTIC,RDLINKINTRTIC,RDLINKZONE;
}