package com.navinfo.dataservice.FosEngine.edit.model;

/**
 * 对象类型
 */
public enum ObjType {

	RDLINK, 
	RDNODE, 
	RDRESTRICTION,
	RDLINKFORM, 
	RDLINKLIMIT,
	RDLINKNAME, 
	RDRESTRICTIONVIA, 
	RDRESTRICTIONDETAIL, 
	RDRESTRICTIONCONDITION, 
	RDNODEFORM, 
	RDNODENAME, 
	RDNODEMESH, 
	RDCROSS, 
	RDCROSSLINK, 
	RDCROSSNODE, 
	RDCROSSNAME,
	RDLINKLIMITTRUNK,
	RDLINKSPEEDLIMIT,
	RDLINKSIDEWALK,
	RDLINKWALKSTAIR,
	RDLINKRTIC,
	RDLINKINTRTIC,
	RDLINKZONE,
	RDSPEEDLIMIT,
	RDLANECONNEXITY,
	RDLANETOPOLOGY,
	RDLANEVIA,
	RDBRANCH,
	RDBRANCHDETAIL,
	RDBRANCHNAME,
	RDBRANCHREALIMAGE,
	RDBRANCHSCHEMATIC,
	RDSIGNBOARD,
	RDSIGNBOARDNAME,
	RDSIGNASREAL,
	RDSERIESBRANCH,
	RDBRANCHVIA,
	
	ADFACE,
	CKEXCEPTION;
}