
UPDATE AU_SERIESPHOTO SET TASK_ID=0 where TASK_ID=${taskId} ;
UPDATE AU_ADAS_GPSTRACK SET TASK_ID=0 where TASK_ID=${taskId} ;
UPDATE AU_MARK SET MERGE_FLAG=0,TASK_ID=0 where TASK_ID=${taskId} AND MERGE_FLAG<>2 AND TYPE in (0,6) AND (Mark_ITEM IN(17,24,77,78) OR (Mark_ITEM=61 AND PARAM_EX IN('限速','解除限速','条件限速开始','条件限速结束'))) ;

UPDATE AU_IX_POI SET GEO_TASK_ID=0,GEO_OPRSTATUS=0 where GEO_TASK_ID=${taskId};
UPDATE AU_IX_POINTADDRESS SET GEO_TASK_ID=0,GEO_OPRSTATUS=0 where GEO_TASK_ID=${taskId};

UPDATE AU_PT_POI SET GEO_TASK_ID=0,GEO_OPRSTATUS=0 where GEO_TASK_ID=${taskId};
UPDATE AU_PT_PLATFORM SET GEO_TASK_ID=0,GEO_OPRSTATUS=0 where GEO_TASK_ID=${taskId};
UPDATE AU_PT_STRAND SET GEO_TASK_ID=0,GEO_OPRSTATUS=0 where GEO_TASK_ID=${taskId};


