
UPDATE AU_SERIESPHOTO SET TASK_ID=${taskId} where PHOTO_ID IN (SELECT PID FROM TEMP_AU_SERIESPHOTO) ;
UPDATE AU_ADAS_GPSTRACK SET TASK_ID=${taskId} where GPSTRACK_ID IN (SELECT PID FROM TEMP_AU_ADAS_GPSTRACK) ;
UPDATE AU_MARK SET TASK_ID=${taskId},MERGE_FLAG=${dmsStatus} where MARK_ID IN (SELECT PID FROM TEMP_AU_MARK) AND MERGE_FLAG=0 AND TYPE in (0,6) AND (Mark_ITEM IN(17,24,77,78) OR (Mark_ITEM=61 AND PARAM_EX IN('限速','解除限速','条件限速开始','条件限速结束'))) ;

UPDATE AU_IX_POI SET GEO_TASK_ID=${taskId},GEO_OPRSTATUS=${dmsStatus} where AUDATA_ID IN (SELECT PID FROM TEMP_IX_POI) AND GEO_OPRSTATUS = 0 AND STATE <>0;
UPDATE AU_IX_POINTADDRESS SET GEO_TASK_ID=${taskId},GEO_OPRSTATUS=${dmsStatus} where AUDATA_ID IN (SELECT PID FROM TEMP_IX_POINTADDRESS) AND GEO_OPRSTATUS = 0 AND STATE <>0;

UPDATE AU_PT_POI SET GEO_TASK_ID=${taskId},GEO_OPRSTATUS=${dmsStatus} where AUDATA_ID IN (SELECT PID FROM TEMP_PT_POI) AND GEO_OPRSTATUS = 0 AND STATE <>0;
UPDATE AU_PT_PLATFORM SET GEO_TASK_ID=${taskId},GEO_OPRSTATUS=${dmsStatus} where AUDATA_ID IN (SELECT PID FROM TEMP_PT_PLATFORM) AND GEO_OPRSTATUS = 0 AND STATE <>0;
UPDATE AU_PT_STRAND SET GEO_TASK_ID=${taskId},GEO_OPRSTATUS=${dmsStatus} where AUDATA_ID IN (SELECT PID FROM TEMP_PT_STRAND) AND GEO_OPRSTATUS = 0 AND STATE <>0;
