INSERT INTO IX_POI (SELECT * FROM IX_POI@GDB_DB_LINK WHERE PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_CONTACT (SELECT * FROM IX_POI_CONTACT@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_NAME (SELECT NAME_ID,POI_PID,NAME_GROUPID,NAME_CLASS,NAME_TYPE,LANG_CODE,NAME,NAME_PHONETIC,KEYWORDS,NIDB_PID,U_RECORD,U_FIELDS FROM IX_POI_NAME@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_ADDRESS (SELECT * FROM IX_POI_ADDRESS@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_ICON (SELECT * FROM IX_POI_ICON@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_FLAG (SELECT * FROM IX_POI_FLAG@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_PHOTO (SELECT * FROM IX_POI_PHOTO@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_AUDIO (SELECT * FROM IX_POI_AUDIO@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_VIDEO (SELECT * FROM IX_POI_VIDEO@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_INTRODUCTION (SELECT * FROM IX_POI_INTRODUCTION@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_ADVERTISEMENT (SELECT * FROM IX_POI_ADVERTISEMENT@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_HOTEL (SELECT * FROM IX_POI_HOTEL@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_ATTRACTION (SELECT * FROM IX_POI_ATTRACTION@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_GASSTATION (SELECT * FROM IX_POI_GASSTATION@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_RESTAURANT (SELECT * FROM IX_POI_RESTAURANT@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_CHARGINGSTATION (SELECT * FROM IX_POI_CHARGINGSTATION@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_CHARGINGPLOT (SELECT * FROM IX_POI_CHARGINGPLOT@GDB_DB_LINK WHERE CHARGING_ID IN (SELECT CHARGING_ID FROM IX_POI_CHARGINGSTATION@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI)));
INSERT INTO IX_POI_CHILDREN (SELECT * FROM IX_POI_CHILDREN@GDB_DB_LINK WHERE CHILD_POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI) );
INSERT INTO IX_POI_PARENT (SELECT GROUP_ID,PARENT_POI_PID,TENANT_FLAG,MEMO,U_RECORD,U_FIELDS FROM IX_POI_PARENT@GDB_DB_LINK WHERE PARENT_POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI) AND GROUP_ID NOT IN (SELECT GROUP_ID FROM IX_POI_PARENT));
INSERT INTO IX_SAMEPOI_PART (SELECT * FROM IX_SAMEPOI_PART@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI) );
INSERT INTO IX_SAMEPOI (SELECT * FROM IX_SAMEPOI@GDB_DB_LINK WHERE GROUP_ID IN (SELECT GROUP_ID FROM IX_SAMEPOI_PART@GDB_DB_LINK WHERE POI_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POI)) AND GROUP_ID NOT IN (SELECT GROUP_ID FROM IX_SAMEPOI));
INSERT INTO IX_POI_NAME_FLAG (SELECT * FROM IX_POI_NAME_FLAG@GDB_DB_LINK WHERE NAME_ID IN (SELECT NAME_iD FROM IX_POI_NAME@GDB_DB_LINK T1,TEMP_RETRIEVE_IX_POI T2 WHERE T1.POI_PID=T2.PID));
INSERT INTO IX_POI_ENTRYIMAGE(SELECT * FROM IX_POI_ENTRYIMAGE@GDB_DB_LINK WHERE POI_PID IN(SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_BUILDING(SELECT * FROM IX_POI_BUILDING@GDB_DB_LINK WHERE POI_PID IN(SELECT PID FROM TEMP_RETRIEVE_IX_POI));
INSERT INTO IX_POI_CARRENTAL(SELECT * FROM IX_POI_CARRENTAL@GDB_DB_LINK WHERE POI_PID IN(SELECT PID FROM TEMP_RETRIEVE_IX_POI));


INSERT INTO IX_POINTADDRESS (SELECT * FROM IX_POINTADDRESS@GDB_DB_LINK WHERE PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POINTADDRESS));
INSERT INTO IX_POINTADDRESS_NAME (SELECT * FROM IX_POINTADDRESS_NAME@GDB_DB_LINK WHERE PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POINTADDRESS));
INSERT INTO IX_POINTADDRESS_NAME_TONE (SELECT * FROM IX_POINTADDRESS_NAME_TONE@GDB_DB_LINK WHERE NAME_ID IN (SELECT NAME_ID FROM IX_POINTADDRESS_NAME@GDB_DB_LINK WHERE PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POINTADDRESS)));
INSERT INTO IX_POINTADDRESS_FLAG (SELECT * FROM IX_POINTADDRESS_FLAG@GDB_DB_LINK WHERE PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POINTADDRESS));
INSERT INTO IX_POINTADDRESS_CHILDREN (SELECT * FROM IX_POINTADDRESS_CHILDREN@GDB_DB_LINK WHERE CHILD_PA_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POINTADDRESS));
INSERT INTO IX_POINTADDRESS_PARENT (SELECT * FROM IX_POINTADDRESS_PARENT@GDB_DB_LINK WHERE PARENT_PA_PID IN (SELECT PID FROM TEMP_RETRIEVE_IX_POINTADDRESS) AND GROUP_ID NOT IN (SELECT GROUP_ID FROM IX_POINTADDRESS_PARENT));

INSERT INTO IX_ANNOTATION (SELECT * FROM IX_ANNOTATION@GDB_DB_LINK WHERE PID IN (SELECT PID FROM TEMP_RETRIEVE_AU_IX_ANNOTATION));
INSERT INTO IX_ANNOTATION_NAME (SELECT * FROM IX_ANNOTATION_NAME@GDB_DB_LINK WHERE PID IN (SELECT PID FROM TEMP_RETRIEVE_AU_IX_ANNOTATION));
INSERT INTO IX_ANNOTATION_FLAG (SELECT * FROM IX_ANNOTATION_FLAG@GDB_DB_LINK WHERE PID IN (SELECT PID FROM TEMP_RETRIEVE_AU_IX_ANNOTATION));
