alter TABLE SC_PLATERES_INFO MODIFY URL VARCHAR2(1000);
alter TABLE SC_PLATERES_INFO MODIFY INFO_CODE VARCHAR2(50);
alter TABLE SC_PLATERES_INFO MODIFY ADMIN_CODE VARCHAR2(30);
alter TABLE SC_PLATERES_INFO MODIFY NEWS_TIME VARCHAR2(200);
alter TABLE SC_PLATERES_INFO MODIFY INFO_CONTENT VARCHAR2(4000);
alter TABLE SC_PLATERES_INFO MODIFY MEMO VARCHAR2(4000);
exit;