UPDATE POI_EDIT_STATUS A SET STATUS = 0,IS_UPLOAD=0,UPLOAD_DATE=NULL,FRESH_VERIFIED=0,RAW_FIELDS=NULL WHERE A.STATUS=3 AND NOT EXISTS (SELECT NULL FROM LOG_OPERATION B,LOG_DETAIL C WHERE A.ROW_ID=C.TB_ROW_ID AND B.OP_ID=C.OP_ID AND (B.COM_STA=0 OR B.REL_STA=0));
DELETE FROM LOG_OPERATION WHERE COM_STA=1 AND REL_STA=1;
DELETE FROM LOG_DETAIL A WHERE NOT EXISTS (SELECT NULL FROM LOG_OPERATION B WHERE B.OP_ID=A.OP_ID);
DELETE FROM LOG_DETAIL_GRID A WHERE NOT EXISTS (SELECT NULL FROM LOG_DETAIL B WHERE A.LOG_ROW_ID=B.ROW_ID);
TRUNCATE TABLE NI_VAL_EXCEPTION_HISTORY;
DELETE FROM CK_RESULT_OBJECT A WHERE NOT EXISTS (SELECT NULL FROM NI_VAL_EXCEPTION B WHERE B.MD5_CODE=A.MD5_CODE);
DELETE FROM CK_EXCEPTION_GRID A WHERE NOT EXISTS (SELECT NULL FROM CK_EXCEPTION B WHERE B.ROW_ID=A.EXCEP_ROW_ID);
DELETE FROM NI_VAL_EXCEPTION_GRID A WHERE NOT EXISTS (SELECT NULL FROM NI_VAL_EXCEPTION B WHERE B.MD5_CODE=A.MD5_CODE);