--CREATE FUNCTION
CREATE OR REPLACE FUNCTION MD5_CLOB(
passwd IN CLOB)
RETURN VARCHAR2
IS
retval varchar2(32);
BEGIN
retval := utl_raw.cast_to_raw(DBMS_OBFUSCATION_TOOLKIT.MD5(INPUT_STRING => passwd)) ;
RETURN retval;
END;
/