TRUNCATE TABLE POI_EDIT_STATUS;
TRUNCATE TABLE POI_DEEP_STATUS;
TRUNCATE TABLE POI_DEEP_WORKITEM;
INSERT INTO POI_EDIT_STATUS(ROW_ID) SELECT ROW_ID FROM IX_POI;
INSERT INTO POI_DEEP_STATUS(ROW_ID) SELECT ROW_ID FROM IX_POI;
INSERT INTO POI_DEEP_WORKITEM(ROW_ID) SELECT ROW_ID FROM IX_POI;
COMMIT;