--SC_ROADNAME_SUFFIX
INSERT INTO SC_ROADNAME_SUFFIX SELECT * FROM SC_ROADNAME_SUFFIX@DBLINK_SMM;
COMMIT;
--SC_ROADNAME_INFIX
INSERT INTO SC_ROADNAME_INFIX SELECT * FROM SC_ROADNAME_INFIX@DBLINK_SMM;
COMMIT;
--SC_ROADNAME_TYPENAME
INSERT INTO SC_ROADNAME_TYPENAME SELECT * FROM SC_ROADNAME_TYPENAME@DBLINK_SMM;
COMMIT;
--TY_CHARACTER_EGALCHAR_EXT
INSERT INTO TY_CHARACTER_EGALCHAR_EXT SELECT * FROM TY_CHARACTER_EGALCHAR_EXT@DBLINK_SMM;
COMMIT;
--SC_ROADNAME_POSITION
INSERT INTO SC_ROADNAME_POSITION SELECT * FROM SC_ROADNAME_POSITION@DBLINK_SMM;
COMMIT;
--SC_ROADNAME_SPLIT_PREFIX
INSERT INTO SC_ROADNAME_SPLIT_PREFIX SELECT * FROM SC_ROADNAME_SPLIT_PREFIX@DBLINK_SMM;
COMMIT;
--SC_ROADNAME_ENGNM_QJ
INSERT INTO SC_ROADNAME_ENGNM_QJ SELECT * FROM SC_ROADNAME_ENGNM_QJ@DBLINK_SMM;
COMMIT;
--TY_CHARACTER_FJT_HZ
INSERT INTO TY_CHARACTER_FJT_HZ SELECT * FROM TY_CHARACTER_FJT_HZ@DBLINK_SMM;
COMMIT;
--TMC_VERSION
INSERT INTO TMC_VERSION SELECT * FROM TMC_VERSION@DBLINK_SMM;
COMMIT;
--TMC_POINT_TRANSLATENAME
INSERT INTO TMC_POINT_TRANSLATENAME SELECT * FROM TMC_POINT_TRANSLATENAME@DBLINK_SMM;
COMMIT;
--TMC_LINE_TRANSLATENAME
INSERT INTO TMC_LINE_TRANSLATENAME SELECT * FROM TMC_LINE_TRANSLATENAME@DBLINK_SMM;
COMMIT;
--TMC_AREA_TRANSLATENAME
INSERT INTO TMC_AREA_TRANSLATENAME SELECT * FROM TMC_AREA_TRANSLATENAME@DBLINK_SMM;
COMMIT;
--TMC_LOCATION_CODE
INSERT INTO TMC_LOCATION_CODE SELECT * FROM TMC_LOCATION_CODE@DBLINK_SMM;
COMMIT;
--TY_CHARACTER_FJT_HM_CHECK
INSERT INTO TY_CHARACTER_FJT_HM_CHECK SELECT * FROM TY_CHARACTER_FJT_HM_CHECK@DBLINK_SMM;
COMMIT;

--M_PARAMETER
INSERT INTO M_PARAMETER SELECT * FROM M_PARAMETER@DBLINK_SMM;
COMMIT;

--TY_NAVICOVPY_WORD
INSERT INTO TY_NAVICOVPY_WORD SELECT * FROM TY_NAVICOVPY_WORD@DBLINK_SMM;
COMMIT;

--TY_NAVICOVPY_PY
INSERT INTO TY_NAVICOVPY_PY SELECT * FROM TY_NAVICOVPY_PY@DBLINK_SMM;
COMMIT;


--TY_CHARACTER_FULL2HALF
INSERT INTO TY_CHARACTER_FULL2HALF SELECT * FROM TY_CHARACTER_FULL2HALF@DBLINK_SMM;
COMMIT;

--TY_NAVICOVPY_KEYWORD
INSERT INTO TY_NAVICOVPY_KEYWORD SELECT * FROM TY_NAVICOVPY_KEYWORD@DBLINK_SMM;
COMMIT;

--TY_NAVICOVPY_KEYWORD_KIND
INSERT INTO TY_NAVICOVPY_KEYWORD_KIND SELECT * FROM TY_NAVICOVPY_KEYWORD_KIND@DBLINK_SMM;
COMMIT;

--SC_POINT_NAMECK
INSERT INTO SC_POINT_NAMECK SELECT * FROM SC_POINT_NAMECK@DBLINK_SMM;
COMMIT;