--SC_ROADNAME_SUFFIX
INSERT INTO SC_ROADNAME_SUFFIX SELECT * FROM SC_ROADNAME_SUFFIX@DBLINK_SMM;
--SC_ROADNAME_INFIX
INSERT INTO SC_ROADNAME_INFIX SELECT * FROM SC_ROADNAME_INFIX@DBLINK_SMM;
--SC_ROADNAME_TYPENAME
INSERT INTO SC_ROADNAME_TYPENAME SELECT * FROM SC_ROADNAME_TYPENAME@DBLINK_SMM;
--TY_CHARACTER_EGALCHAR_EXT
INSERT INTO TY_CHARACTER_EGALCHAR_EXT SELECT * FROM TY_CHARACTER_EGALCHAR_EXT@DBLINK_SMM;
--SC_ROADNAME_POSITION
INSERT INTO SC_ROADNAME_POSITION SELECT * FROM SC_ROADNAME_POSITION@DBLINK_SMM;
--SC_ROADNAME_SPLIT_PREFIX
INSERT INTO SC_ROADNAME_SPLIT_PREFIX SELECT * FROM SC_ROADNAME_SPLIT_PREFIX@DBLINK_SMM;
--SC_ROADNAME_ENGNM_QJ
INSERT INTO SC_ROADNAME_ENGNM_QJ SELECT * FROM SC_ROADNAME_ENGNM_QJ@DBLINK_SMM;
--TY_CHARACTER_FJT_HZ
INSERT INTO TY_CHARACTER_FJT_HZ SELECT * FROM TY_CHARACTER_FJT_HZ@DBLINK_SMM;
--TMC_VERSION
INSERT INTO TMC_VERSION SELECT * FROM TMC_VERSION@DBLINK_SMM;
--TMC_POINT_TRANSLATENAME
INSERT INTO TMC_POINT_TRANSLATENAME SELECT * FROM TMC_POINT_TRANSLATENAME@DBLINK_SMM;
--TMC_LINE_TRANSLATENAME
INSERT INTO TMC_LINE_TRANSLATENAME SELECT * FROM TMC_LINE_TRANSLATENAME@DBLINK_SMM;
--TMC_AREA_TRANSLATENAME
INSERT INTO TMC_AREA_TRANSLATENAME SELECT * FROM TMC_AREA_TRANSLATENAME@DBLINK_SMM;
--TMC_LOCATION_CODE
INSERT INTO TMC_LOCATION_CODE SELECT * FROM TMC_LOCATION_CODE@DBLINK_SMM;
--TY_CHARACTER_FJT_HM_CHECK
------------------------------------------------------

COMMIT;
