
-- CREATE FUNCTION
CREATE OR REPLACE FUNCTION SFRT (STR IN VARCHAR2)
   RETURN VARCHAR
IS
BEGIN
   RETURN NVL (REPLACE (REPLACE (STR, '\', '\\'), '"', '\"'), '\N');
END;
/
-- CREATE TABLES
--ci_para_rd_name
CREATE TABLE CI_PARA_RD_NAME(
  NAME VARCHAR2(50) DEFAULT NULL,
  ADMIN_ID NUMBER(10) DEFAULT NULL,
  NAME_LEN NUMBER(10) DEFAULT NULL
);
/
CREATE INDEX IX_CI_PARA_AD_ADMIN  ON  CI_PARA_RD_NAME(ADMIN_ID);
/
CREATE INDEX IX_CI_PARA_RD_NAME_LEN  ON  CI_PARA_RD_NAME(NAME_LEN);
/
