-- CREATE TEMP TABLE
CREATE TABLE TEMP_DEL_POI_001(
PID NUMBER(10)
);
CREATE TABLE TEMP_DEL_POI_PC_001(
PID NUMBER(10));
CREATE TABLE TEMP_DEL_POI_SP_001(
PID NUMBER(10));
-- SELECT POI ROWS
INSERT INTO TEMP_DEL_POI_001 SELECT PID FROM IX_POI P,SC_POINT_POICODE_NEW@DBLINK_RMS S
WHERE P.KIND_CODE=S.KIND_CODE AND S.KG_DES='GD';
-- SELECT POI PARENT CHILDREN ROWS
INSERT INTO TEMP_DEL_POI_PC_001 (SELECT P.GROUP_ID FROM IX_POI_PARENT P,TEMP_DEL_POI_001 T WHERE P.PARENT_POI_PID=T.PID
 UNION ALL
SELECT P.GROUP_ID FROM IX_POI_CHILDREN P,TEMP_DEL_POI_001 T WHERE P.CHILD_POI_PID=T.PID) ; 
DELETE FROM TEMP_DEL_POI_PC_001 A WHERE ROWID != (SELECT MAX(B.ROWID) FROM TEMP_DEL_POI_PC_001 B WHERE B.PID=A.PID);
-- SELECT SAMEPOI ROWS
INSERT INTO TEMP_DEL_POI_SP_001 (SELECT P.GROUP_ID FROM IX_SAMEPOI_PART P,TEMP_DEL_POI_001 T WHERE P.POI_PID=T.PID) ; 
DELETE FROM TEMP_DEL_POI_SP_001 A WHERE ROWID != (SELECT MAX(B.ROWID) FROM TEMP_DEL_POI_SP_001 B WHERE B.PID=A.PID);

-- DELETE SANMEPOI ROWS
DELETE FROM IX_SAMEPOI_PART P WHERE P.GROUP_ID IN (SELECT PID FROM TEMP_DEL_POI_SP_001);
DELETE FROM IX_SAMEPOI P WHERE P.GROUP_ID IN (SELECT PID FROM TEMP_DEL_POI_SP_001);
-- DELETE PARENT CHILDREN ROWS
DELETE FROM IX_POI_CHILDREN P WHERE P.GROUP_ID IN (SELECT PID FROM TEMP_DEL_POI_PC_001);
DELETE FROM IX_POI_PARENT P WHERE P.GROUP_ID IN (SELECT PID FROM TEMP_DEL_POI_PC_001);
-- DELETE POI ROWS
DELETE FROM IX_POI P WHERE P.PID IN (SELECT PID FROM TEMP_DEL_POI_001 );
DELETE FROM IX_POI_NAME_FLAG P WHERE P.NAME_ID IN(SELECT T2.NAME_ID FROM IX_POI_NAME T2, TEMP_DEL_POI_001 T WHERE T2.POI_PID=T.PID);                             
DELETE FROM IX_POI_NAME_TONE P WHERE P.NAME_ID IN(SELECT T2.NAME_ID FROM IX_POI_NAME T2, TEMP_DEL_POI_001 T WHERE T2.POI_PID=T.PID);                             
DELETE FROM IX_POI_NAME P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T );
DELETE FROM IX_POI_ADDRESS P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T );
DELETE FROM IX_POI_CONTACT P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T );
DELETE FROM IX_POI_FLAG P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T );
DELETE FROM IX_POI_ENTRYIMAGE P WHERE P.POI_PID IN (SELECT T.PID FROM TEMP_DEL_POI_001 T);
DELETE FROM IX_POI_ICON P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T );
DELETE FROM IX_POI_PHOTO P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T );
DELETE FROM IX_POI_AUDIO P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T );
DELETE FROM IX_POI_VIDEO P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T );

DELETE FROM IX_POI_BUILDING P WHERE P.POI_PID IN (SELECT T.PID FROM TEMP_DEL_POI_001 T);  
DELETE FROM IX_POI_DETAIL P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 );	
DELETE FROM IX_POI_BUSINESSTIME P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T ); 
DELETE FROM IX_POI_INTRODUCTION P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T );
DELETE FROM IX_POI_ADVERTISEMENT P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T );
DELETE FROM IX_POI_GASSTATION P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T );
DELETE FROM IX_POI_CHARGINGSTATION P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T );
DELETE FROM IX_POI_CHARGINGPLOT P WHERE POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T );
DELETE FROM IX_POI_CHARGINGPLOT_PH P WHERE POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T ); 
DELETE FROM IX_POI_PARKING P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 );
DELETE FROM IX_POI_ATTRACTION P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T );
DELETE FROM IX_POI_HOTEL P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T );
DELETE FROM IX_POI_RESTAURANT P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 T );		
DELETE FROM IX_POI_EVENT P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 );	
DELETE FROM IX_POI_CARRENTAL P WHERE P.POI_PID IN (SELECT PID FROM TEMP_DEL_POI_001 );

COMMIT;
