package com.navinfo.dataservice.engine.check.core;

public enum VariableName {
	RDLINK_PID,
	RDNODE_PID,
	RDGATE_INLINKPID,
	RDGATE_OUTLINKPID,
	RDDIRECTROUTE_PID,
	RDSLOPE_PID,
	RDWARNINGINFO_PID,
	RDBRANCH_PID,
	RDVOICEGUIDE_PID,
	RDTOLLGATE_PID,
	RDGATE_PID,
	RDLANE_PID,
	RDELECTRONICEYE_PID;	
}
