INSERT INTO IX_POI (SELECT * FROM IX_POI@PARENT_VERSION_DB_LINK WHERE TASK_ID=${taskId});
INSERT INTO IX_POI_CONTACT (SELECT C.* FROM IX_POI_CONTACT@PARENT_VERSION_DB_LINK C,IX_POI@PARENT_VERSION_DB_LINK I WHERE I.TASK_ID=${taskId} AND I.PID=C.POI_PID);
INSERT INTO IX_POI_NAME (SELECT C.* FROM IX_POI_NAME@PARENT_VERSION_DB_LINK C,IX_POI@PARENT_VERSION_DB_LINK I WHERE I.TASK_ID=${taskId} AND I.PID=C.POI_PID);
INSERT INTO IX_POI_ADDRESS (SELECT C.* FROM IX_POI_ADDRESS@PARENT_VERSION_DB_LINK C,IX_POI@PARENT_VERSION_DB_LINK I WHERE I.TASK_ID=${taskId} AND I.PID=C.POI_PID);
