CREATE TABLE &1 AS SELECT * FROM IX_POI_CHARGINGPLOT C WHERE EXISTS(SELECT 1 FROM &2 T WHERE C.POI_PID = T.POI_PID) AND C.U_RECORD <> 2;

UPDATE IX_POI_CHARGINGPLOT C SET C.MANUFACTURER=(SELECT DISTINCT T.NEW_MANUFACTURER FROM &2 T WHERE T.POI_PID = C.POI_PID) WHERE EXISTS(SELECT 1 FROM TEMP_CHARGE_20171013 T WHERE T.POI_PID = C.POI_PID);

UPDATE IX_POI_CHARGINGPLOT C SET C.FACTORY_NUM=(SELECT DISTINCT T.NEW_FACTORY_NUM FROM &2 T WHERE T.POI_PID = C.POI_PID) WHERE EXISTS(SELECT 1 FROM TEMP_CHARGE_20171013 T WHERE T.POI_PID = C.POI_PID) AND C.FACTORY_NUM IS NULL;

COMMIT;
EXIT;