prompt PL/SQL Developer import file
prompt Created on 2017年2月9日 by jch
set feedback off
set define off
drop table SC_POINT_CODE2LEVEL;
prompt Creating SC_POINT_CODE2LEVEL...
create table SC_POINT_CODE2LEVEL
(
  ID            NUMBER(4) not null,
  KIND_NAME     VARCHAR2(200) not null,
  KIND_CODE     VARCHAR2(8) not null,
  OLD_POI_LEVEL VARCHAR2(20),
  NEW_POI_LEVEL VARCHAR2(20),
  MEMO          VARCHAR2(200),
  DESCRIPT      VARCHAR2(200),
  KG_FLAG       VARCHAR2(2) not null,
  HM_FLAG       VARCHAR2(3) not null,
  CHAIN         VARCHAR2(4),
  RATING        NUMBER(2),
  FLAGCODE      VARCHAR2(12),
  CATEGORY      NUMBER(2),
  TYPE          VARCHAR2(3)
)
tablespace GDB_DATA
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 80K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table SC_POINT_CODE2LEVEL
  add constraint CKC_CODE2LEVEL
  check (TYPE in (0,1));

prompt Disabling triggers for SC_POINT_CODE2LEVEL...
alter table SC_POINT_CODE2LEVEL disable all triggers;
prompt Deleting SC_POINT_CODE2LEVEL...
delete from SC_POINT_CODE2LEVEL;
commit;
prompt Loading SC_POINT_CODE2LEVEL...
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (321, '家装建材零售', '130703', 'B3|B4|C', 'B4', null, '16夏修改KIND_NAME,由“建材、洁具零售”改为“家装建材零售”；需求溯源号：TPD-127', 'KG', 'DHM', null, null, null, 1, '1');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (322, '灯饰零售', '130704', 'B3|C', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (323, '家居用品零售', '130705', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (324, '五金零售', '130701', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (325, '母婴用品、儿童用品零售', '130303', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (326, '报刊零售', '130403', 'C', 'C', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (327, '电脑及数码产品', '130602', 'B2|C', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (328, '通信设备零售', '130603', 'B3|B4|C', 'B4', null, '16冬修改NEW_POI_LEVEL,由B3改为B4，修改CATEGORY，由3改为1', 'KG', 'DHM', null, null, null, 1, '1');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (332, '加气站', '230216', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (333, '电动汽车充电站', '230218', 'B1', 'B1', null, '15冬修改KIND_NAME，2050722', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (334, '厂家一览表内汽车零售', '140101', 'A', 'A', null, '15春新分类改善，等级一样，整合为1个，其类型改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (336, '厂家一览表内汽车零售及修理', '140301', 'A', 'A', null, '15春新分类改善，等级一样，整合为1个，其类型改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (338, '厂家一览表内汽车修理', '140201', 'A', 'A', null, '15春新分类改善，等级一样，整合为1个，其类型改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (361, '公司', '220100', 'A', 'A', null, '15冬修改CATEGORY值，删FLAG_CODE值，新增chain,需求溯源号：CR001658；16冬修改CATEGORY，由3变为2', 'KG', 'DHM', '4012', null, null, 2, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (366, '厂家一览表外汽车零售及修理', '140302', 'B1|C', 'B1', null, '15春新分类改善，等级一样，整合为1个，其类型改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (377, '厂家一览表内二手车交易', '140303', 'A', 'A', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (425, '溜冰场', '180110', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (426, '夜总会、歌舞厅、迪厅', '180202', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (427, '健身房、俱乐部、康乐宫、电玩城', '180203', 'B2', 'B2', null, '15秋修改KIND_NAME(20150421)', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (428, '棋牌室', '180204', 'C', 'C', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (429, '垂钓', '180109', 'B2|C', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (430, '区、县政府', '190109', 'A', 'A', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (431, '乡镇政府', '190110', 'A', 'A', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (432, '地级市级政府机关', '190103', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (433, '区级政府机关', '190104', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (434, '县级政府机关', '190105', 'B3', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (435, '区级政府机关(广州市）', '190106', 'B2', 'B2', null, null, 'KG', 'D', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (436, '货运火车站', '230107', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (437, '火车站出发到达', '230105', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (438, '理发', '210204', 'B3|B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '1');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (439, '美容/美体', '210205', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (440, '美甲、纹身', '210206', 'B4|C', 'B4', null, '15夏修改，将KIND_NAME由"美容院、理发店"改为"美甲、纹身"', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (441, '洗浴、按摩服务', '210207', 'B3|C', 'B3', null, '15夏修改，将KIND_NAME由"洗浴服务"改为"洗浴、按摩服务"', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (442, '银行', '150101', 'B1', 'B1', null, '15春新分类改善，等级一样，整合为1个，其类型改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (469, '专业性团体', '190301', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (470, '行业性团体', '190302', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (471, '洗染服务', '210201', 'B3|C', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (472, '缴费营业厅', '210303', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (473, '邮政服务', '210213', 'B2', 'B2', null, '16冬修改CATEGORY，由6改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (474, '物流快运', '230130', 'B3|C', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (475, '货物自提点', '210218', 'B3', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (476, '旅行社', '200405', 'B3|C', 'B3', null, '16冬修改CATEGORY，由3改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (576, '磁悬浮主点（行人导航）', '230115', 'B2', 'B2', '行人导航', '14秋NEW_POI_LEVEL由“”（空）变更为“B2”；16冬修改CATEGORY，由2改为1', 'GD', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (577, '公共电汽车客运（行人导航）', '230101', 'B2', 'B2', '行人导航', '14秋NEW_POI_LEVEL由“”（空）变更为“B2”；16冬修改CATEGORY，由2改为1', 'GD', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (578, '出租车客运（行人导航）', '230117', 'B2', 'B2', '行人导航', '14秋NEW_POI_LEVEL由“”（空）变更为“B2”；16冬修改CATEGORY，由2改为1', 'GD', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (579, '乡\镇', '260000', 'B2', 'B2', 'Hamlet数据', '14秋NEW_POI_LEVEL由“”（空）变更为“B2”', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (580, '村\屯', '260100', 'B2', 'B2', 'Hamlet数据', '14秋NEW_POI_LEVEL由“”（空）变更为“B2”', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (581, '水系', '260200', 'B2', 'B2', 'Hamlet数据', '14秋NEW_POI_LEVEL由“”（空）变更为“B2”', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (582, '水上公交（行人导航）', '230123', 'B2', 'B2', '行人导航', '14秋NEW_POI_LEVEL由“”（空）变更为“B2”；16冬修改CATEGORY，由2改为1', 'GD', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (583, '水上公交出入口（行人导航）', '230124', 'B2', 'B2', '行人导航', '14秋NEW_POI_LEVEL由“”（空）变更为“B2”；16冬修改CATEGORY，由2改为1', 'GD', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (586, '公共电汽车客运出入口（行人导航）', '230102', 'B2', 'B2', '行人导航', '14秋NEW_POI_LEVEL由“”（空）变更为“B2”；16冬修改CATEGORY，由2改为1', 'GD', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (588, '长途客运站出入口（行人导航）', '230110', 'B2', 'B2', '行人导航', '14秋NEW_POI_LEVEL由“”（空）变更为“B2”；16冬修改CATEGORY，由2改为1', 'GD', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (589, '小巴出入口（行人导航）', '230120', 'B2', 'B2', '行人导航', '14秋NEW_POI_LEVEL由“”（空）变更为“B2”；16冬修改CATEGORY，由2改为1', 'GD', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (590, '缆车站（行人导航）', '230121', 'B2', 'B2', '行人导航', '14秋NEW_POI_LEVEL由“”（空）变更为“B2”；16冬修改CATEGORY，由2改为1', 'GD', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (591, '缆车站出入口（行人导航）', '230122', 'B2', 'B2', '行人导航', '14秋NEW_POI_LEVEL由“”（空）变更为“B2”；16冬修改CATEGORY，由2改为1', 'GD', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (592, '出租车客运出入口（行人导航）', '230118', 'B2', 'B2', '行人导航', '14秋NEW_POI_LEVEL由“”（空）变更为“B2”；16冬修改CATEGORY，由2改为1', 'GD', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (201, '星级酒店', '120101', 'B1', 'B1', null, '15秋修改RATING值20150720；16冬修改CATEGORY，由5改为3', 'KG', 'DHM', null, 1, null, 3, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (202, '星级酒店', '120101', 'A', 'A', null, '16冬修改CATEGORY，由5改为3', 'KG', 'DHM', null, 4, null, 3, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (203, '星级酒店', '120101', 'A', 'A', null, '16冬修改CATEGORY，由5改为3', 'KG', 'DHM', null, 5, null, 3, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (204, '一般旅馆', '120102', 'B2|B3', 'B3', null, '16冬修改NEW_POI_LEVEL,由B2改为B3', 'KG', 'DHM', null, null, null, 1, '1');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (205, '度假村、疗养院', '180302', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (206, '酒店公寓', '120103', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (207, '普通出租公寓', '120104', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (208, '动物园', '180308', 'A', 'A', null, '14秋NEW_POI_LEVEL由“B1”变更为“A”', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (209, '植物园', '180309', 'A', 'A', null, '14秋NEW_POI_LEVEL由“B1”变更为“A”', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (210, '水族馆', '180310', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (211, '高尔夫球场', '180105', 'A', 'A', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (596, '献血屋', '170110', 'B3', 'B3', null, '14冬新增', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (4, '快餐', '110200', 'B2|B3|C', 'B3', null, '14秋NEW_POI_LEVEL由“B1”变更为“B2”；16冬修改NEW_POI_LEVEL,由B2改为B3,修改CATEGORY，由3改为1', 'KG', 'DHM', null, null, null, 1, '1');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (10, '异国风味', '110102', 'B2|B3', 'B3', null, '14秋NEW_POI_LEVEL由“B1”变更为“B2”；16冬修改NEW_POI_LEVEL,由B2改为B3', 'KG', 'DHM', null, null, null, 1, '1');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (11, '中餐馆', '110101', 'B2|B3|C', 'B3', null, '14秋NEW_POI_LEVEL由“B1”变更为“B2”；16冬修改NEW_POI_LEVEL,由B2改为B3', 'KG', 'DHM', null, null, null, 1, '1');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (12, '酒吧', '110301', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (13, '茶楼、茶艺馆', '110304', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (14, '咖啡馆', '110303', 'B1', 'B1', null, '15春新分类改善，等级一样，整合为1个，其类型改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (18, '冷饮店', '110302', 'B1|B3|C', 'B3', null, '16冬修改NEW_POI_LEVEL,由B1改为B3', 'KG', 'DHM', null, null, null, 1, '1');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (19, '地方风味店、地方名店', '110103', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (20, '其他零售', '130800', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (21, '宗教用品零售', '130807', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (22, '丧葬用品零售', '130806', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (23, '旧货市场', '130804', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (24, '便利零售', '130105', 'B2|B3', 'B3', null, '16冬修改NEW_POI_LEVEL,由B2改为B3,修改CATEGORY，由3改为1', 'KG', 'DHM', null, null, null, 1, '1');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (35, '超级市场零售', '130106', 'B2|B3', 'B3', null, '15冬修改CATEGORY，需求溯源号：CR001690；16冬修改NEW_POI_LEVEL,由B2改为B3，修改CATEGORY，由3改为1', 'KG', 'DHM', null, null, null, 1, '1');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (239, '派出所', '190202', 'B1', 'B1', null, '16冬修改CATEGORY，由6改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (240, '交警队', '190203', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (241, '消防', '190204', 'B1', 'B1', null, null, 'KG', 'HM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (242, '图书馆', '160203', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (243, '医疗机构', '170100', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (244, '综合医院', '170101', 'A', 'A', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (245, '专科医院', '170102', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (246, '私人诊所', '170103', 'B3', 'B3', null, '16夏修改MHM_DES，由“HM”改为“DHM”；需求溯源号：TPD-127', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (1, '网吧', '180205', 'B4', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (247, '医院内部设施', '170104', 'B3', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (248, '急诊科/室', '170105', 'B3', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (249, '体检机构', '170109', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (250, '社区医疗', '170106', 'B2|C', 'B2', null, '15冬修改KIND_NAME', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (251, '牙科诊所', '170107', 'B2|C', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (252, '公园', '180304', 'A', 'A', null, '14秋NEW_POI_LEVEL由“B1”变更为“A”', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (253, '广场', '180306', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (254, '会议中心、展览中心', '200101', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (255, '培训中心', '200102', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
commit;
prompt 100 records committed...
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (256, '疾病预防控制及防疫', '170108', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (257, '宠物医院', '210105', 'B4', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (258, '职业中介服务', '200404', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (259, '法律服务', '200300', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (260, '律师服务', '200301', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (261, '会计事务所', '200401', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (262, '审计事务所', '200402', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (263, '知识产权服务', '200403', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (264, '司法鉴定所', '200302', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (265, '养老院、福利院', '170201', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (266, '殡葬服务', '210210', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (267, '公共厕所', '210215', 'B2', 'B2', null, '16冬修改CATEGORY，由6改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (268, '街心公园', '180305', 'B2', 'B2', null, null, 'KG', 'HM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (269, '客货运输', '230100', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (270, '客运火车站', '230103', 'A', 'A', null, '14秋NEW_POI_LEVEL由“B1”变更为“A”', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (271, '轻轨/地铁站出入口', '230111', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (272, '客运汽车站', '230108', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (273, '磁悬浮出入口', '230114', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (274, '机场', '230126', 'A', 'A', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (275, '机场出发/到达', '230127', 'A', 'A', null, '14秋NEW_POI_LEVEL由“B1”变更为“A”', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (276, '城市候机楼', '230129', 'A', 'A', null, '14秋NEW_POI_LEVEL由“B1”变更为“A”', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (277, '机场出发/到达门', '230128', 'A', 'A', null, '14秋NEW_POI_LEVEL由“B1”变更为“A”', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (278, '港口、码头', '230125', 'A', 'A', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (279, '票务中心/定票处', '210302', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (280, '高速服务区', '230206', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (281, '高速停车区', '230207', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (282, '收费站', '230208', 'B1', 'B1', null, '14秋NEW_POI_LEVEL由“B2”变更为“B1”，16冬修改CATEGORY，由6改为1', 'K', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (283, '超限超载检测站', '230219', 'B2', 'B2', null, '14秋NEW_POI_LEVEL由“B4”变更为“B2”', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (284, '刹车失灵缓冲区', '230220', 'B2', 'B2', null, '14秋NEW_POI_LEVEL由“B4”变更为“B2”', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (285, '刹车冷却区', '230221', 'B4', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (286, '风景名胜', '180400', 'A', 'A', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (287, '风景名胜售票点', '210304', 'B4', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (288, '寺庙、道观、庵', '190401', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (289, '宗教', '190400', 'B1', 'B1', null, '14秋NEW_POI_LEVEL由“B4”变更为“B1”', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (290, '天主教', '190402', 'B1', 'B1', null, '14秋NEW_POI_LEVEL由“B4”变更为“B1”', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (291, '基督教', '190403', 'B1', 'B1', null, '14秋NEW_POI_LEVEL由“B4”变更为“B1”', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (292, '伊斯兰教', '190404', 'B1', 'B1', null, '14秋NEW_POI_LEVEL由“B4”变更为“B1”', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (293, '美术馆', '160206', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (294, '博物馆、纪念馆、展览馆、陈列馆', '160205', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (295, '档案馆', '160204', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (296, '文化活动中心', '160208', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (297, '科技馆', '160207', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (298, '文工团、歌舞团、艺术团', '160209', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (299, '出版社', '160201', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (300, '广播、电视、电影', '160202', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (301, '陵园、公墓', '210211', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (304, '音像制品及电子出版物零售', '130404', 'B3|C', 'B3', null, '16冬修改CATEGORY，由6改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (312, '钟表、摄影器材零售', '130405', 'B3', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (313, '眼镜零售', '130302', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (314, '工艺礼品', '130407', 'B4|C', 'B4', null, '16夏修改KIND_NAME,由“工艺美术品”改为“工艺礼品”；需求溯源号：TPD-127', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (315, '玩具/动漫零售', '130410', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (316, '图书零售', '130402', 'B2|C', 'B2', null, '16冬修改CATEGORY，由7改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (319, '五金、家具及室内装修材料零售', '130700', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (599, '星级酒店', '120101', 'B1', 'B1', null, '15春因为新分类改善而增加；16冬修改CATEGORY，由5改为3', 'KG', 'DHM', null, 13, null, 3, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (600, '星级酒店', '120101', 'B1', 'B1', null, '15春因为新分类改善而增加；16冬修改CATEGORY，由5改为3', 'KG', 'DHM', null, 16, null, 3, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (601, '星级酒店', '120101', 'B1', 'B1', null, '15春因为新分类改善而增加；16冬修改CATEGORY，由5改为3', 'KG', 'DHM', null, 17, null, 3, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (602, '星级酒店', '120101', 'A', 'A', null, '15春因为新分类改善而增加；16冬修改CATEGORY，由5改为3', 'KG', 'DHM', null, 14, null, 3, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (603, '星级酒店', '120101', 'A', 'A', null, '15春因为新分类改善而增加；16冬修改CATEGORY，由5改为3', 'KG', 'DHM', null, 15, null, 3, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (605, '婚姻介绍所', '210219', 'B3', 'B3', null, '15夏新增20150129', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (606, '商业综合体', '200105', 'B1', 'B1', null, '15夏新增20150129', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (479, '证券', '150103', 'B3', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (480, '典当拍卖、贷款担保', '150104', 'B3', 'B3', null, '16夏修改KIND_NAME，由“典当、拍卖”改为“典当拍卖、贷款担保”；需求溯源号：TPD-127', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (481, '摄影扩印服务', '210214', 'B3|C', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (482, '婚纱影楼', '210212', 'B3', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (483, '婚庆服务', '210209', 'B3|C', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (484, '高等教育', '160105', 'A', 'A', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (485, '幼儿园/托儿所', '160101', 'B2', 'B2', null, '16冬修改CATEGORY，由6改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (486, '小学', '160102', 'B2', 'B2', null, '16冬修改CATEGORY，由6改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (487, '中学', '160103', 'B2', 'B2', null, '16冬修改CATEGORY，由6改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (488, '驾校', '160109', 'B3', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (489, '中专', '160104', 'B3', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (490, '教育', '160100', 'B3|B4', 'B4', null, '16冬修改NEW_POI_LEVEL,由B3改为B4', 'KG', 'DHM', null, null, null, 1, '1');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (491, '教学楼', '160106', 'B4', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (492, '院/系', '160107', 'B4', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (493, '学校报名处', '160108', 'B4', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (494, '科研机构及附属机构', '240100', 'B3', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (495, '小区', '120201', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (496, '住宅楼', '120202', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (497, '公司', '220100', 'B2|B3', 'B3', null, '15冬修改CATEGORY值，需求溯源号：CR001658；；16冬修改CATEGORY，由3变为2', 'KG', 'DHM', null, null, null, 2, '1');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (498, '厂矿', '220200', 'B3', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (499, '工业园', '220300', 'B3', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (500, '其他事业单位', '220400', 'B3', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (501, '农、林、牧、渔生产', '250100', 'B4', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (502, '农、林、牧、渔服务业', '250200', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (503, '保险业', '150200', 'B2', 'B2', null, '16冬修改CATEGORY，由3改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (510, '电信服务', '210301', 'B2', 'B2', null, '16冬修改CATEGORY，由3改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (518, '家政服务', '210101', 'C', 'C', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (519, '房地产中介服务', '210216', 'C', 'C', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (520, '赛马会', '180206', 'B1', 'B1', null, null, 'KG', 'HM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (521, '赛狗场', '180211', 'B1', 'B1', null, '15秋改KIND_CODE(20150421)', 'KG', 'HM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (522, '博彩', '180207', 'B1', 'B1', null, null, 'KG', 'HM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (523, '彩票投注站', '180208', 'C', 'C', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (524, '大厦/写字楼', '200103', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (525, '商务中心/会馆', '200104', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (526, '租赁服务', '200200', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (527, '其他服务', '210400', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (528, '送水站', '210104', 'C', 'C', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (529, '服装裁剪服装定制', '210202', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (530, '皮草/鞋/包保养', '210203', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (56, '商品交易/批发市场零售', '130101', 'B3', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
commit;
prompt 200 records committed...
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (57, '百货商场零售', '130102', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (58, '百货商店零售', '130103', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (59, '日杂店', '130104', 'C', 'C', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (60, '食品、饮料及烟酒制品零售', '130200', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (61, '烟酒制品零售', '130204', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (62, '副食品零售', '130207', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (63, '地方土特产零售', '130205', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (64, '保健品零售', '130206', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (65, '电器零售', '130601', 'B2|B3', 'B3', null, '16夏修改KIND_NAME,由“电器商场”改为“电器零售”；需求溯源号：TPD-127；16冬修改NEW_POI_LEVEL,由B2改为B3，修改CATEGORY，由3改为1', 'KG', 'DHM', null, null, null, 1, '1');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (69, '服装、箱包零售', '130301', 'B3|B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '1');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (70, '体育用品专卖店', '130401', 'B3', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (71, '化妆品专卖', '130304', 'B3|C', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (72, '茶叶、茶具零售', '130203', 'B3|B4|C', 'B4', null, '16冬修改NEW_POI_LEVEL,由B3改为B4', 'KG', 'DHM', null, null, null, 1, '1');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (73, '糕点、面包零售', '130201', 'B3|C', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (74, '花鸟鱼虫零售', '130801', 'B3|C', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (75, '宠物及宠物用品零售', '130803', 'B3|C', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (76, '文化办公用品零售', '130411', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (77, '办公服务', '210217', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (78, '古玩字画零售', '130408', 'B3|C', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (79, '药品零售', '130501', 'B2|B3', 'B3', null, '16冬修改NEW_POI_LEVEL,由B2改为B3', 'KG', 'DHM', null, null, null, 1, '1');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (80, '医疗用品及器材零售', '130502', 'B3', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (81, '乐器零售', '130409', 'B3|C', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (82, '农贸产品综合销售', '130202', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (83, '珠宝首饰零售', '130406', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (84, '加油站', '230215', 'B1', 'B1', null, '15春新分类改善，等级一样，整合为1个，其类型改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (94, '停车场', '230210', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (95, '换乘停车场（P+R停车场）', '230213', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (96, '货车专用停车场', '230214', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (97, '汽车租赁', '200201', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (142, '厂家一览表外二手车交易', '140304', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (150, '公司', '220100', 'A', 'A', null, '15冬修改CATEGORY值，删FLAG_CODE值，新增chain,需求溯源号：CR001658；16冬修改CATEGORY，由3变为2', 'KG', 'DHM', '412F', null, null, 2, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (174, '汽车用品零售', '140104', 'B1|C', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (175, '汽车零配件零售', '140103', 'B2|C', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (176, '汽车养护', '140203', 'B1|C', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (177, '自行车、电动车、摩托车销售', '130805', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (178, '机动车检测场', '140202', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (198, '星级酒店', '120101', 'B1', 'B1', null, '16冬修改CATEGORY，由5改为3', 'KG', 'DHM', null, 3, null, 3, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (199, '星级酒店', '120101', 'B1', 'B1', null, '16冬修改CATEGORY，由5改为3', 'KG', 'DHM', null, 7, null, 3, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (607, '露营房车营地', '230226', 'B1', 'B1', null, '15秋新增,需求溯源号:CR001555', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (608, '商务服务', '200400', 'B2', 'B2', null, '15冬新增，需求溯源号：CR001657', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (609, '考试中心', '160110', 'B3', 'B3', null, '15冬新增，需求溯源号：CR001693', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (610, '电动汽车充电桩', '230227', 'B1', 'B1', null, '15冬新增20150722,需求溯源号:PPRM-128', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (200, '星级酒店', '120101', 'B1', 'B1', null, '16冬修改CATEGORY，由5改为3', 'KG', 'DHM', null, 8, null, 3, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (212, '高尔夫练习场', '180106', 'A', 'A', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (213, '保龄球馆', '180103', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (214, '滑雪场', '180104', 'A', 'A', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (215, '游乐园', '180307', 'A', 'A', null, '14秋NEW_POI_LEVEL由“B1”变更为“A”', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (216, '天然浴场', '180303', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (217, '赛马场', '180107', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (218, '电影院', '180209', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (219, '艺术表演场馆', '180210', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (220, '运动场馆', '180100', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (221, '羽毛球场', '180101', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (222, '网球场', '180102', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (223, 'KTV', '180201', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (224, '农家乐、民俗游', '180301', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (225, '政府及管理机构', '190100', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (226, '行政办公大厅', '190111', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (227, '驻京、驻地方办事处', '190112', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (228, '外国大使馆/领事馆', '190501', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (229, '国际组织', '190500', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (230, '基层群众自治组织', '190113', 'B3', 'B3', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (231, '国家级政府机关', '190101', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (232, '省级政府机关', '190102', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (233, '省、直辖市政府', '190107', 'A', 'A', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (234, '市政府', '190108', 'A', 'A', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (235, '签证处', '190502', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (236, '边检口岸', '190114', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (237, '公安机关', '190200', 'B1', 'B1', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (238, '公安局', '190201', 'B1', 'B1', null, '16冬修改CATEGORY，由6改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (531, '家电维修', '210103', 'B4|C', 'B4', null, '16冬修改CATEGORY，由3改为1', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (532, '摩托车、自行车、电动车维护与保养', '210102', 'C', 'C', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (533, '立交桥', '230202', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (534, '桥', '230201', 'B2', 'B2', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (547, '道路名', '230222', 'B4', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (567, 'WI-FI', '240206', 'B4', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (572, '专线小巴站主点', '230119', 'B2', 'B2', '行人导航', '14秋NEW_POI_LEVEL由“”（空）变更为“B2”；16冬修改CATEGORY，由2改为1', 'GD', 'HM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (574, '轻轨/地铁站主点（行人导航）', '230112', 'B2', 'B2', '行人导航', '14秋NEW_POI_LEVEL由“”（空）变更为“B2”；16冬修改CATEGORY，由2改为1', 'GD', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (320, '家具零售', '130702', 'B4|C', 'B4', null, null, 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (611, '加水站', '230228', 'B2', 'B2', null, '16冬新增；需求溯源号：PPRM-353', 'KG', 'DHM', null, null, null, 1, '0');
insert into SC_POINT_CODE2LEVEL (ID, KIND_NAME, KIND_CODE, OLD_POI_LEVEL, NEW_POI_LEVEL, MEMO, DESCRIPT, KG_FLAG, HM_FLAG, CHAIN, RATING, FLAGCODE, CATEGORY, TYPE)
values (612, '紧急停车带', '230229', 'B2', 'B2', null, '16冬新增；需求溯源号：PPRM-353', 'KG', 'DHM', null, null, null, 1, '0');
commit;
prompt 281 records loaded
prompt Enabling triggers for SC_POINT_CODE2LEVEL...
alter table SC_POINT_CODE2LEVEL enable all triggers;
set feedback on
set define on
prompt Done.
EXIT;