CREATE OR REPLACE PACKAGE AUTO_GET_SCHEMA IS

  -- Author  : XUXIAOBO
  -- Created : 2012/8/27 17:32:10

  PROCEDURE GET_SCHEMA(OUT_TABLE_CLOB OUT CLOB,INDEX_OUT_LOB OUT CLOB,VIEW_OUT_LOB OUT CLOB,SEQ_OUT_LOB OUT CLOB);

END AUTO_GET_SCHEMA;
/
CREATE OR REPLACE PACKAGE BODY AUTO_GET_SCHEMA IS
    PROCEDURE GET_SCHEMA(OUT_TABLE_CLOB OUT CLOB,INDEX_OUT_LOB OUT CLOB,VIEW_OUT_LOB OUT CLOB,SEQ_OUT_LOB  OUT CLOB) IS

    TEMP_OBJ    CLOB;
    CURSOR TABLE_CUR_GET IS SELECT DBMS_METADATA.GET_DDL('TABLE',TABLE_NAME) TABLESNAME FROM USER_TABLES;  --��
   -- CURSOR INDEX_CUR_GET IS SELECT DBMS_METADATA.GET_DDL('INDEX',OBJECT_NAME) INDEXSNAME FROM USER_OBJECTS WHERE OBJECT_TYPE = 'INDEX'; -- ����
    CURSOR INDEX_CUR_GET IS  SELECT DBMS_METADATA.GET_DDL('INDEX',OBJECT_NAME) INDEXSNAME  FROM USER_OBJECTS  T WHERE OBJECT_TYPE = 'INDEX' 
          AND T.OBJECT_NAME NOT IN (
     SELECT C.CONSTRAINT_NAME FROM USER_CONSTRAINTS C WHERE C.CONSTRAINT_TYPE in ('P','U')
    );
    CURSOR VIEW_CUR_GET IS SELECT  DBMS_METADATA.GET_DDL('VIEW',OBJECT_NAME) VIEWSNAME FROM USER_OBJECTS WHERE OBJECT_TYPE = 'VIEW';  -- ��ͼ

    CURSOR SEQ_CUR_GET IS  SELECT  DBMS_METADATA.GET_DDL('SEQUENCE',OBJECT_NAME) VIEWSNAME FROM USER_OBJECTS WHERE OBJECT_TYPE = 'SEQUENCE';  -- ����
    


    BEGIN
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'STORAGE',FALSE);
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'TABLESPACE',FALSE);
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SEGMENT_ATTRIBUTES',FALSE);



    FOR REC IN TABLE_CUR_GET  LOOP
         TEMP_OBJ := REC.TABLESNAME;
         OUT_TABLE_CLOB := OUT_TABLE_CLOB||TEMP_OBJ||';';
    END LOOP;

    IF TABLE_CUR_GET%ISOPEN THEN
        CLOSE TABLE_CUR_GET;
    END IF;

    FOR REC IN INDEX_CUR_GET  LOOP
           TEMP_OBJ := REC.INDEXSNAME;
           INDEX_OUT_LOB := INDEX_OUT_LOB||TEMP_OBJ||';';
    END LOOP;

    IF INDEX_CUR_GET%ISOPEN THEN
        CLOSE INDEX_CUR_GET;
    END IF;

    FOR REC IN VIEW_CUR_GET  LOOP
           TEMP_OBJ := REC.VIEWSNAME;
           VIEW_OUT_LOB := VIEW_OUT_LOB||TEMP_OBJ||';';
    END LOOP;

    IF VIEW_CUR_GET%ISOPEN THEN
        CLOSE VIEW_CUR_GET;
    END IF;
 
    FOR REC IN SEQ_CUR_GET  LOOP
           TEMP_OBJ := REC.VIEWSNAME;
           SEQ_OUT_LOB := SEQ_OUT_LOB||TEMP_OBJ||';';
    END LOOP;

    IF SEQ_CUR_GET%ISOPEN THEN
        CLOSE SEQ_CUR_GET;
    END IF;



    EXCEPTION
        WHEN OTHERS THEN
        IF TABLE_CUR_GET%ISOPEN THEN
           CLOSE TABLE_CUR_GET;
        END IF;

        IF INDEX_CUR_GET%ISOPEN THEN
            CLOSE INDEX_CUR_GET;
        END IF;

        IF VIEW_CUR_GET%ISOPEN THEN
            CLOSE VIEW_CUR_GET;
        END IF;

	IF SEQ_CUR_GET%ISOPEN THEN
            CLOSE SEQ_CUR_GET;
        END IF;
        DBMS_OUTPUT.PUT_LINE('GET_SCHEMA ' || SQLERRM);
    END;
END AUTO_GET_SCHEMA;
/
