DECLARE 
 CURSOR T_CURSOR IS SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME LIKE 'TEMP%';
BEGIN
  FOR R_REC IN T_CURSOR LOOP
    EXECUTE IMMEDIATE 'DROP TABLE '||R_REC.TABLE_NAME;
  END LOOP;
END;
/

EXIT;
