-- sys_message
ALTER TABLE SYS_MESSAGE ADD MSG_TITLE VARCHAR2(50);
ALTER TABLE SYS_MESSAGE ADD PUSH_USER_ID NUMBER(10);

ALTER TABLE SYS_MESSAGE_READ_LOG ADD MSG_STATUS NUMBER(2) DEFAULT 1 NOT NULL;
-- glm_tables
UPDATE GLM_TABLES SET OBJ_NAME='IX_POI',OBJ_PID_COL='PID' WHERE TABLE_NAME='IX_POI';
commit;

EXIT;