-- sys_message
ALTER TABLE SYS_MESSAGE ADD MSG_TITLE VARCHAR2(50);
ALTER TABLE SYS_MESSAGE ADD PUSH_USER_ID NUMBER(10);
ALTER TABLE SYS_MESSAGE_READ_LOG ADD MSG_STATUS NUMBER(2) DEFAULT 1 NOT NULL;

EXIT;