TRUNCATE TABLE TEMP_AD_ADMIN_${suffix};
TRUNCATE TABLE TEMP_AD_ADMIN_RG_${suffix};
TRUNCATE TABLE TEMP_AD_FACE_${suffix};
TRUNCATE TABLE TEMP_AD_LINK_${suffix};
TRUNCATE TABLE TEMP_AD_NODE_${suffix};
TRUNCATE TABLE TEMP_SC_MODEL_MATCH_G_${suffix};
TRUNCATE TABLE TEMP_AU_SPECIALCASE_${suffix};
TRUNCATE TABLE TEMP_CMG_BUILDFACE_${suffix};
TRUNCATE TABLE TEMP_CMG_BUILDING_${suffix};
TRUNCATE TABLE TEMP_CMG_BUILDLINK_${suffix};
TRUNCATE TABLE TEMP_CMG_BUILDNODE_${suffix};

TRUNCATE TABLE TEMP_CM_BUILDFACE_${suffix};
--TRUNCATE TABLE TEMP_CM_BUILDING_${suffix};
--TRUNCATE TABLE TEMP_CM_BUILDLINK_${suffix};
--TRUNCATE TABLE TEMP_CM_BUILDNODE_${suffix};


TRUNCATE TABLE TEMP_CM_BLOCKLINK_${suffix};
TRUNCATE TABLE TEMP_CM_BLOCKNODE_${suffix};
TRUNCATE TABLE TEMP_CM_BLOCK_${suffix};
TRUNCATE TABLE TEMP_CM_BUILDING_${suffix};
TRUNCATE TABLE TEMP_CM_BUILDLINK_${suffix};
TRUNCATE TABLE TEMP_CM_BUILDNODE_${suffix};
TRUNCATE TABLE TEMP_CM_ROADLINK_${suffix};
TRUNCATE TABLE TEMP_CM_ROADNODE_${suffix};
TRUNCATE TABLE TEMP_CM_ROAD_${suffix};
TRUNCATE TABLE TEMP_FILTER_RD_LINK_${suffix};
TRUNCATE TABLE TEMP_FILTER_RD_NODE_${suffix};
TRUNCATE TABLE TEMP_FILTER_RW_LINK_${suffix};
TRUNCATE TABLE TEMP_FILTER_RW_NODE_${suffix};
--TRUNCATE TABLE TEMP_FILTER_TMC_POINT_${suffix};
TRUNCATE TABLE TEMP_IX_POI_${suffix};
TRUNCATE TABLE TEMP_FILTER_IX_POI_${suffix};
TRUNCATE TABLE TEMP_LC_FACE_${suffix};
TRUNCATE TABLE TEMP_LC_FEATURE_${suffix};
TRUNCATE TABLE TEMP_LC_LINK_${suffix};
TRUNCATE TABLE TEMP_LC_NODE_${suffix};
TRUNCATE TABLE TEMP_LU_FACE_${suffix};
TRUNCATE TABLE TEMP_LU_FEATURE_${suffix};
TRUNCATE TABLE TEMP_LU_LINK_${suffix};
TRUNCATE TABLE TEMP_LU_NODE_${suffix};
TRUNCATE TABLE TEMP_PT_LINE_${suffix};
TRUNCATE TABLE TEMP_PT_POI_${suffix};
TRUNCATE TABLE TEMP_FILTER_PT_POI_${suffix};
TRUNCATE TABLE TEMP_PT_POI_GROUP_${suffix};
TRUNCATE TABLE TEMP_PT_PLATFORM_${suffix};
TRUNCATE TABLE TEMP_PT_STRAND_${suffix};
TRUNCATE TABLE TEMP_RD_BRANCH_${suffix};
TRUNCATE TABLE TEMP_RD_BRANCH_DETAIL_${suffix};
TRUNCATE TABLE TEMP_RD_CHAIN_${suffix};
TRUNCATE TABLE TEMP_RD_CROSSWALK_${suffix};
TRUNCATE TABLE TEMP_RD_CROSS_${suffix};
TRUNCATE TABLE TEMP_RD_DIRECTROUTE_${suffix};
TRUNCATE TABLE TEMP_RD_GATE_${suffix};
TRUNCATE TABLE TEMP_RD_GSC_${suffix};
TRUNCATE TABLE TEMP_RD_INTER2_${suffix};
TRUNCATE TABLE TEMP_RD_INTER_${suffix};
TRUNCATE TABLE TEMP_FILTER_RD_LANE_${suffix};
TRUNCATE TABLE TEMP_RD_LANE_${suffix};
TRUNCATE TABLE TEMP_RD_LANE_CONNEXITY_${suffix};
TRUNCATE TABLE TEMP_RD_LANE_TOPOLOGY_${suffix};
TRUNCATE TABLE TEMP_RD_LINK_${suffix};
TRUNCATE TABLE TEMP_RD_LINK_NAMEID_${suffix};
TRUNCATE TABLE TEMP_RD_LINK_RELATEID_${suffix};
TRUNCATE TABLE TEMP_RD_LINK_TMC_${suffix};
TRUNCATE TABLE TEMP_RD_NODE_${suffix};
TRUNCATE TABLE TEMP_RD_OBJECT_${suffix};
TRUNCATE TABLE TEMP_RD_RESTRICTION_${suffix};
TRUNCATE TABLE TEMP_RD_RESTRICTION_DETAIL_${suffix};
TRUNCATE TABLE TEMP_RD_ROAD2_${suffix};
TRUNCATE TABLE TEMP_RD_ROAD_${suffix};
TRUNCATE TABLE TEMP_RD_SE_${suffix};
TRUNCATE TABLE TEMP_RD_SIGNBOARD_${suffix};
TRUNCATE TABLE TEMP_RD_SIGNPOST_${suffix};
TRUNCATE TABLE TEMP_RD_TOLLGATE_${suffix};
TRUNCATE TABLE TEMP_RD_VIRCONNECT_${suffix};
TRUNCATE TABLE TEMP_RD_VOICEGUIDE_${suffix};
TRUNCATE TABLE TEMP_RD_SPEEDLIMIT_${suffix};
TRUNCATE TABLE TEMP_RD_ELECTRONICEYE_${suffix};
TRUNCATE TABLE TEMP_RTIC_INFO_${suffix};
TRUNCATE TABLE TEMP_RW_FEATURE_${suffix};
TRUNCATE TABLE TEMP_RW_LINK_${suffix};
TRUNCATE TABLE TEMP_SAME_LINK_${suffix};
TRUNCATE TABLE TEMP_SAME_NODE_${suffix};
TRUNCATE TABLE TEMP_TMC_POINT_${suffix};
TRUNCATE TABLE TEMP_ZONE_FACE_${suffix};
TRUNCATE TABLE TEMP_ZONE_FEATURE_${suffix};
TRUNCATE TABLE TEMP_ZONE_LINK_${suffix};
TRUNCATE TABLE TEMP_ZONE_NODE_${suffix};

TRUNCATE TABLE TEMP_HW_${suffix};
TRUNCATE TABLE TEMP_HW_ESTAB_${suffix};
TRUNCATE TABLE TEMP_HW_MESH_${suffix};


TRUNCATE TABLE TEMP_IX_HAMLET_${suffix};
TRUNCATE TABLE TEMP_IX_POINTADDRESS_${suffix};
TRUNCATE TABLE TEMP_IX_POI_GROUP_${suffix};


TRUNCATE TABLE TEMP_HW_POSITION_${suffix};
TRUNCATE TABLE TEMP_HW_ROUTE_${suffix};

TRUNCATE TABLE TEMP_RD_LANE_TOPO_DETAIL_${suffix};
TRUNCATE TABLE TEMP_IX_POINTADDRESS_GROUP_${suffix};
TRUNCATE TABLE TEMP_FILTER_IX_POINTADDRESS_${suffix};
TRUNCATE TABLE TEMP_AU_MARK_${suffix};
TRUNCATE TABLE TEMP_AU_GPSTRACK_${suffix};
TRUNCATE TABLE TEMP_AU_PHOTO_${suffix};
TRUNCATE TABLE TEMP_AU_AUDIO_${suffix};
TRUNCATE TABLE TEMP_AU_VIDEO_${suffix};


TRUNCATE TABLE TEMP_RD_VARIABLE_SPEED_${suffix};
TRUNCATE TABLE TEMP_IX_SAMEPOI_${suffix};
TRUNCATE TABLE TEMP_RD_LINK_NAMEGID_${suffix};
TRUNCATE TABLE TEMP_AU_SERIESPHOTO_${suffix};
TRUNCATE TABLE TEMP_AU_ADAS_MARK_${suffix};
TRUNCATE TABLE TEMP_AU_ADAS_GPSTRACK_${suffix};
TRUNCATE TABLE TEMP_IX_ANNOTATION_${suffix};
TRUNCATE TABLE TEMP_PT_COMPANY_${suffix};
TRUNCATE TABLE TEMP_PT_SYSTEM_${suffix};
TRUNCATE TABLE TEMP_ADAS_LINK_${suffix};
TRUNCATE TABLE TEMP_ADAS_NODE_${suffix};

TRUNCATE TABLE TEMP_PT_ETA_ACCESS_${suffix};
TRUNCATE TABLE TEMP_PT_ETA_STOP_${suffix};
TRUNCATE TABLE TEMP_PT_ETA_LINE_${suffix};
TRUNCATE TABLE TEMP_PT_TRANSFER_${suffix};


TRUNCATE TABLE TEMP_IX_POI_POINUM_${suffix};

TRUNCATE TABLE TEMP_EXP_PARAMTERS_${suffix};

--NEW 2012/9/3
TRUNCATE TABLE TEMP_AD_ADMIN_GROUP_${suffix};
TRUNCATE TABLE TEMP_RD_SLOPE_${suffix};

--NEW 200模型升级
TRUNCATE TABLE TEMP_RD_NATGUD_JUN_${suffix};
TRUNCATE TABLE TEMP_HWY_JUNCTION_${suffix};
TRUNCATE TABLE TEMP_HWY_JCT_${suffix};
--TRUNCATE TABLE TEMP_RD_NODE_INFO_ADAS_${suffix};--210模型删除
TRUNCATE TABLE TEMP_IX_NATGUD_${suffix};





TRUNCATE TABLE TEMP_PARENT_CHILD_${suffix};

TRUNCATE TABLE TEMP_PARENT_CHILD_PC_${suffix};
TRUNCATE TABLE TEMP_IX_POI_RP00_${suffix};
TRUNCATE TABLE TEMP_FILTER_IX_POI_NK_${suffix};
TRUNCATE TABLE TEMP_IX_POI_NK_${suffix};


TRUNCATE TABLE TEMP_AU_GPSTRACK_GROUP_${suffix};
TRUNCATE TABLE TEMP_AU_POI_FIELD_TASK_${suffix};
TRUNCATE TABLE TEMP_AU_PA_FIELD_TASK_${suffix};

--NEW 240模型升级
TRUNCATE TABLE TEMP_ELECEYE_GROUP_${suffix};
