
UPDATE AU_SERIESPHOTO SET TASK_ID=0 where TASK_ID=${taskId} ;
UPDATE AU_ADAS_GPSTRACK SET TASK_ID=0 where TASK_ID=${taskId} ;
UPDATE AU_MARK SET MERGE_FLAG=0,TASK_ID=0 where TASK_ID=${taskId} AND MERGE_FLAG<>2 AND TYPE in (0,6) AND (Mark_ITEM IN(17,24,77,78) OR (Mark_ITEM=61 AND PARAM_EX IN('限速','解除限速','条件限速开始','条件限速结束'))) ;

UPDATE AU_IX_POI SET ATT_TASK_ID=0,ATT_OPRSTATUS=0 where ATT_TASK_ID=${taskId};
UPDATE AU_IX_POINTADDRESS SET ATT_TASK_ID=0,ATT_OPRSTATUS=0 where ATT_TASK_ID=${taskId};

UPDATE AU_IX_ANNOTATION SET GEO_TASK_ID=0,GEO_OPRSTATUS=0 where GEO_TASK_ID=${taskId};
UPDATE AU_IX_ANNOTATION SET ATT_TASK_ID=0,ATT_OPRSTATUS=0 where ATT_TASK_ID=${taskId};

UPDATE AU_PT_POI SET ATT_TASK_ID=0,ATT_OPRSTATUS=0 where ATT_TASK_ID=${taskId};

UPDATE AU_PT_PLATFORM SET ATT_TASK_ID=0,ATT_OPRSTATUS=0 where ATT_TASK_ID=${taskId};
UPDATE AU_PT_LINE SET ATT_TASK_ID=0,ATT_OPRSTATUS=0 where ATT_TASK_ID=${taskId};
UPDATE AU_PT_STRAND SET ATT_TASK_ID=0,ATT_OPRSTATUS=0 where ATT_TASK_ID=${taskId};

UPDATE AU_PT_COMPANY SET ATT_TASK_ID=0,ATT_OPRSTATUS=0 where ATT_TASK_ID=${taskId};
UPDATE AU_PT_SYSTEM SET ATT_TASK_ID=0,ATT_OPRSTATUS=0 where ATT_TASK_ID=${taskId};
UPDATE AU_PT_TRANSFER SET ATT_TASK_ID=0,ATT_OPRSTATUS=0 where ATT_TASK_ID=${taskId};

UPDATE AU_PT_ETA_STOP SET ATT_TASK_ID=0,ATT_OPRSTATUS=0 where ATT_TASK_ID=${taskId};
UPDATE AU_PT_ETA_ACCESS SET ATT_TASK_ID=0,ATT_OPRSTATUS=0 where ATT_TASK_ID=${taskId};
UPDATE AU_PT_ETA_LINE SET ATT_TASK_ID=0,ATT_OPRSTATUS=0 where ATT_TASK_ID=${taskId};

