
UPDATE AU_SERIESPHOTO SET TASK_ID=${taskId} where PHOTO_ID IN (SELECT PID FROM TEMP_AU_SERIESPHOTO) ;
UPDATE AU_ADAS_GPSTRACK SET TASK_ID=${taskId} where GPSTRACK_ID IN (SELECT PID FROM TEMP_AU_ADAS_GPSTRACK) ;

