set mydir="%mydir%"
echo %mydir%
copy %mydir%\api\api-dropbox\target\*.jar .\target\ &
copy %mydir%\api\api-edit\target\*.jar .\target\ &
copy %mydir%\api\api-fcc\target\*.jar .\target\ &
copy %mydir%\api\api-job\target\*.jar .\target\ &
copy %mydir%\api\api-man\target\*.jar .\target\ &
copy %mydir%\api\api-metadata\target\*.jar .\target\ &
copy %mydir%\api\api-render\target\*.jar .\target\ &
copy %mydir%\api\api-statics\target\*.jar .\target\ &
copy %mydir%\api\biz-commons\target\*.jar .\target\ &
copy %mydir%\biz-commons\target\*.jar .\target\ &
copy %mydir%\commons\target\*.jar .\target\ &
copy %mydir%\dao\dao-fcc-data\target\*.jar .\target\ &
copy %mydir%\dao\dao-glm-data\target\*.jar .\target\ &
copy %mydir%\dao\dao-mq\target\*.jar .\target\ &
copy %mydir%\dao\dao-photo\target\*.jar .\target\ &
copy %mydir%\dao\dao-shm\target\*.jar .\target\ &
copy %mydir%\edit-control\edit-control-app\target\*.jar .\target\ &
copy %mydir%\edit-control\edit-control-column\target\*.jar .\target\ &
copy %mydir%\edit-control\edit-control-row\target\*.jar .\target\ &
copy %mydir%\engine\datahub\target\*.jar .\target\ &
copy %mydir%\engine\engine-check\target\*.jar .\target\ &
copy %mydir%\engine\engine-dropbox\target\*.jar .\target\ &
copy %mydir%\engine\engine-edit\target\*.jar .\target\ &
copy %mydir%\engine\engine-editplus\target\*.jar .\target\ &
copy %mydir%\engine\engine-fcc\target\*.jar .\target\ &
copy %mydir%\engine\engine-file\target\*.jar .\target\ &
copy %mydir%\engine\engine-man\target\*.jar .\target\ &
copy %mydir%\engine\engine-meta\target\*.jar .\target\ &
copy %mydir%\engine\engine-photo\target\*.jar .\target\ &
copy %mydir%\engine\engine-statics\target\*.jar .\target\ &
copy %mydir%\engine\engine-sys\target\*.jar .\target\ &
copy %mydir%\scripts-interface\target\*.jar .\target\ &
copy %mydir%\toolbox\cop-waistcoat\target\*.jar .\target\ &
copy %mydir%\toolbox\diff-core\target\*.jar .\target\ &
copy %mydir%\toolbox\export-core\target\*.jar .\target\ &
copy %mydir%\toolbox\import-core\target\*.jar .\target\ &
copy %mydir%\toolbox\job-datahub\target\*.jar .\target\ &
copy %mydir%\toolbox\job-edit\target\*.jar .\target\ &
