copy E:\workspace\fm_road\DataService_yunfma\DataService\api\api-dropbox\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\api\api-edit\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\api\api-fcc\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\api\api-job\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\api\api-man\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\api\api-metadata\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\api\api-render\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\api\api-statics\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\api\biz-commons\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\biz-commons\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\commons\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\dao\dao-fcc-data\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\dao\dao-glm-data\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\dao\dao-mq\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\dao\dao-photo\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\dao\dao-shm\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\edit-control\edit-control-app\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\edit-control\edit-control-column\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\edit-control\edit-control-row\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\engine\datahub\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\engine\engine-check\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\engine\engine-dropbox\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\engine\engine-edit\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\engine\engine-editplus\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\engine\engine-fcc\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\engine\engine-file\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\engine\engine-man\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\engine\engine-meta\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\engine\engine-photo\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\engine\engine-statics\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\engine\engine-sys\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\scripts-interface\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\toolbox\cop-waistcoat\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\toolbox\diff-core\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\toolbox\export-core\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\toolbox\import-core\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\toolbox\job-datahub\target\*.jar .\target\ &
copy E:\workspace\fm_road\DataService_yunfma\DataService\toolbox\job-edit\target\*.jar .\target\ &
