
-- Table structure for MULTISRC_FM_SYNC
CREATE TABLE MULTISRC_FM_SYNC(
	SID NUMBER(10) NOT NULL,
	SYNC_STATUS NUMBER(4) NOT NULL,
	SYNC_TIME TIMESTAMP,
	JOB_ID NUMBER(10) NOT NULL,
	ZIP_FILE VARCHAR2(128),
	DB_TYPE NUMBER(1),
	CONSTRAINT PK_MS_FM_SYNC PRIMARY KEY(SID)
);


CREATE SEQUENCE MULTISRC_FM_SYNC_SEQ
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999
 START WITH 1
 CACHE 20

