
-- Table structure for FM_MULTISRC_SYNC
CREATE TABLE FM_MULTISRC_SYNC(
	SID NUMBER(10) NOT NULL,
	SYNC_STATUS NUMBER(4) NOT NULL,
	LAST_SYNC_TIME TIMESTAMP,
	SYNC_TIME TIMESTAMP,
	JOB_ID NUMBER(10) NOT NULL,
	ZIP_FILE VARCHAR2(128),
	CONSTRAINT PK_FM_MS_SYNC PRIMARY KEY(SID)
);

CREATE SEQUENCE FM_MULTISRC_SYNC_SEQ
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999
 START WITH 1
 CACHE 20


