WHENEVER SQLERROR CONTINUE;
-- fill db_server
INSERT INTO DB_SERVER(SERVER_ID,SERVER_TYPE,SERVER_IP,SERVER_PORT,SERVICE_NAME,BIZ_TYPE,DESCP)
 VALUES(DB_SERVER_SEQ.NEXTVAL,'ORACLE','192.168.3.227',1521,'orcl','nationRoad,metaRoad,gen2Au','');
INSERT INTO DB_SERVER(SERVER_ID,SERVER_TYPE,SERVER_IP,SERVER_PORT,SERVICE_NAME,BIZ_TYPE,DESCP)
 VALUES(DB_SERVER_SEQ.NEXTVAL,'ORACLE','192.168.4.131',1521,'orcl','desDayAll,desMon,desDayPoi,fmMan','');
INSERT INTO DB_SERVER(SERVER_ID,SERVER_TYPE,SERVER_IP,SERVER_PORT,SERVICE_NAME,BIZ_TYPE,DESCP)
 VALUES(DB_SERVER_SEQ.NEXTVAL,'ORACLE','192.168.4.61',1521,'orcl','regionRoad','');
INSERT INTO DB_SERVER(SERVER_ID,SERVER_TYPE,SERVER_IP,SERVER_PORT,SERVICE_NAME,BIZ_TYPE,DESCP)
 VALUES(DB_SERVER_SEQ.NEXTVAL,'ORACLE','192.168.4.62',1521,'orcl','copVersion','');
INSERT INTO DB_SERVER(SERVER_ID,SERVER_TYPE,SERVER_IP,SERVER_PORT,SERVICE_NAME,BIZ_TYPE,DESCP)
 VALUES(DB_SERVER_SEQ.NEXTVAL,'MONGO','192.168.4.220',30000,NULL,'fmStat','');
-- fill db_hub
INSERT INTO DB_HUB VALUES(DB_SEQ.NEXTVAL,NULL,'app_user','n@vidms',1,'GDB_DATA',NULL,
(SELECT SERVER_ID FROM DB_SERVER WHERE SERVER_IP='192.168.3.227' AND SERVER_PORT='1521'),NULL,2，SYSDATE,'ADMIN DB');
INSERT INTO DB_HUB VALUES(DB_SEQ.NEXTVAL,NULL,'app_user','Navinfo1!',1,'users',NULL,
(SELECT SERVER_ID FROM DB_SERVER WHERE SERVER_IP='192.168.4.131' AND SERVER_PORT='1521'),NULL,2，SYSDATE,'ADMIN DB');
INSERT INTO DB_HUB VALUES(DB_SEQ.NEXTVAL,NULL,'app_user','Navinfo1!',1,'users',NULL,
(SELECT SERVER_ID FROM DB_SERVER WHERE SERVER_IP='192.168.4.61' AND SERVER_PORT='1521'),NULL,2，SYSDATE,'ADMIN DB');
INSERT INTO DB_HUB VALUES(DB_SEQ.NEXTVAL,NULL,'app_user','Navinfo1!',1,'users',NULL,
(SELECT SERVER_ID FROM DB_SERVER WHERE SERVER_IP='192.168.4.62' AND SERVER_PORT='1521'),NULL,2，SYSDATE,'ADMIN DB');
 COMMIT;
EXIT;
