 CREATE TABLE  "TY_NAVICOVPY_KEYWORD" 
   (	"KEYWORD" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"KEYWORDPY" VARCHAR2(255 CHAR), 
	"ADMINAREA" VARCHAR2(255 CHAR), 
	"PRIORITY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ID" NUMBER NOT NULL ENABLE, 
	"FREQUENCY" NUMBER, 
	"KIND" VARCHAR2(255 CHAR), 
	 CONSTRAINT "METADATA_TY_KEYWORD_01" PRIMARY KEY ("ID") ENABLE
   ) ;
  CREATE TABLE  "TY_NAVICOVPY_KEYWORD_KIND" 
   (	"KIND" VARCHAR2(255 CHAR), 
	"KEYWORD_ID" NUMBER NOT NULL ENABLE,
	"CHAIN" VARCHAR2(4 CHAR),
	CONSTRAINT "MD_TY_KEYWORD_KIND_01" PRIMARY KEY ("KIND","KEYWORD_ID","CHAIN") ENABLE
   ) ;
  CREATE TABLE  "TY_NAVICOVPY_WORD2ENG" 
   (	"ID" NUMBER(6,0) NOT NULL ENABLE, 
	"WORD" VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	"PY" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"PY2" VARCHAR2(100 CHAR), 
	"ADMIN_AREA" VARCHAR2(64 CHAR), 
	 CONSTRAINT "CONGDDFD" PRIMARY KEY ("ID") ENABLE
   ) ;
  CREATE TABLE  "TY_CHARACTER_HZ" 
   (	"HZ" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"STROKE" VARCHAR2(255 CHAR), 
	"JFT" NUMBER(1,0), 
	"TADICALS" VARCHAR2(50 CHAR), 
	"SIGHT_WORD" NUMBER(1,0)
   ) ;
  CREATE TABLE  "TY_CHARACTER_EGALCHAR_BASIC" 
   (	"TYPE_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"BASE_TYPE" VARCHAR2(50 CHAR), 
	"EXTENTION_TYPE" VARCHAR2(50 CHAR), 
	"SCOPE" VARCHAR2(250 CHAR), 
	"REMARK" VARCHAR2(250 CHAR), 
	 CONSTRAINT "METADATA_TY_CHARBASIC_01" PRIMARY KEY ("TYPE_ID") ENABLE
   ) ;
  CREATE TABLE  "TY_CHARACTER_EGALCHAR_EXT" 
   (	"EXTENTION_TYPE" VARCHAR2(50 CHAR), 
	"CHARACTER" VARCHAR2(50 CHAR)
   ) ;
  CREATE TABLE  "TY_CHARACTER_FULL2HALF" 
   (	"HALF_WIDTH" VARCHAR2(10 CHAR), 
	"H_UNICODE" NUMBER(10,0), 
	"H_ANSI" NUMBER(10,0), 
	"FULL_WIDTH" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"F_UNICODE" NUMBER(10,0), 
	"F_ANSI" NUMBER(10,0), 
	"SERIAL_ID" NUMBER
   ) ;
  CREATE TABLE  "M_PARAMETER" 
   (	"NAME" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"PARAMETER" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(200 CHAR) NOT NULL ENABLE
   ) ;


     CREATE TABLE  "TY_CHARACTER_FJT_HZ" 
   (	"FT" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"JT" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CONVERT" NUMBER NOT NULL ENABLE, 
	"FTORDER" NUMBER(2,0) NOT NULL ENABLE, 
	 CONSTRAINT "FJT_HZ" PRIMARY KEY ("FT") ENABLE
   ) ;
  CREATE TABLE  "TY_COORD_CONV_GRID" 
   (	"X_NUM" NUMBER(5,0), 
	"Y_NUM" NUMBER(5,0), 
	"X1" NUMBER(10,5), 
	"Y1" NUMBER(10,5), 
	"X2" NUMBER(10,5), 
	"Y2" NUMBER(10,5), 
	"X3" NUMBER(10,5), 
	"Y3" NUMBER(10,5), 
	"X4" NUMBER(10,5), 
	"Y4" NUMBER(10,5)
   ) ;

    CREATE TABLE  "TY_NAVICOVPY_PY" 
   (	"SERIAL_ID" NUMBER NOT NULL ENABLE, 
	"JT" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"PY" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"PYORDER" NUMBER(2,0) NOT NULL ENABLE, 
	"PY2" VARCHAR2(10 CHAR), 
	"FT" VARCHAR2(10 CHAR), 
	"TONE" NUMBER(2,0), 
	 CONSTRAINT "METADATA_TY_PY_01" PRIMARY KEY ("SERIAL_ID") ENABLE
   ) ;
  CREATE TABLE  "TY_NAVICOVPY_WORD" 
   (	"SERIAL_ID" NUMBER NOT NULL ENABLE, 
	"WORD" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"PY" VARCHAR2(200 CHAR) NOT NULL ENABLE, 
	"PY2" VARCHAR2(200 CHAR), 
	"ADMINAREA" VARCHAR2(6 CHAR), 
	"PY3" VARCHAR2(200 CHAR), 
	 CONSTRAINT "METADATA_TY_WORD_01" PRIMARY KEY ("SERIAL_ID") ENABLE
   ) ;
  CREATE TABLE  "TY_COORD_PARAM" 
   (	"NAME" VARCHAR2(100 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 CHAR), 
	"PARAM" VARCHAR2(100 CHAR)
   ) ;

    CREATE TABLE  "TY_CHARACTER_FJT_HM_CHECK" 
   (	"ID" NUMBER(5,0) NOT NULL ENABLE, 
	"HZ" VARCHAR2(8 CHAR) NOT NULL ENABLE, 
	"CORRECT" VARCHAR2(20 CHAR), 
	"KG_FLAG" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"HM_FLAG" VARCHAR2(2 CHAR) NOT NULL ENABLE, 
	"MEMO" VARCHAR2(256 CHAR), 
	"TYPE" NUMBER(2,0), 
	 CONSTRAINT "CODHNG" PRIMARY KEY ("ID") ENABLE
   );