CREATE TABLE "DIFF_RESULT"
  (
    "DIFF_ID"      VARCHAR2(32 CHAR) NOT NULL ENABLE,
    "TABLE_NAME"   VARCHAR2(50 CHAR),
    "ROW_PK"       VARCHAR2(4000 CHAR),
    "LEFT_ROWID"   VARCHAR2(50 CHAR),
    "RIGHT_ROWID"  VARCHAR2(50 CHAR),
    "MERGE_ACTION" NUMBER(1,0),
    "DIFF_COLS"    VARCHAR2(4000 CHAR),
    "DIFF_TYPE"    NUMBER(1,0),
    "VERSION_ID"   NUMBER(10,0)
  );
  
CREATE TABLE "DIFF_OPERATE_LOG"
  (
    "OPERATE_LOG_ID"   VARCHAR2(32 CHAR) NOT NULL ENABLE,
    "OPERATE_STATE_ID" NUMBER(10,0),
    "VERSION_ID"       NUMBER(10,0),
    "ID"               NUMBER(10,0),
    "TASK_ID"          VARCHAR2(50 CHAR),
    "OPERATE_ID"       NUMBER(10,0),
    "OPERATE_NAME"     VARCHAR2(500 CHAR),
    "INNER_ID"         NUMBER(10,0),
    "TABLE_NAME"       VARCHAR2(50 CHAR),
    "OBJECT_NAME"      VARCHAR2(50 CHAR),
    "OBJECT_ID"        NUMBER(10,0),
    "DML_TYPE"         NUMBER(1,0),
    "GEOMETRY"         VARCHAR2(4000 CHAR),
    "UUID"             VARCHAR2(32 CHAR),
    "HIS_TYPE"         NUMBER(1,0),
    "REF_ID"           VARCHAR2(32 CHAR),
    "CHANG_COL"        VARCHAR2(1000 CHAR),
    "OPERATE_DESC"     VARCHAR2(4000 CHAR),
    "OPERATION_RUNTIME" DATE,
    "FEATURE_RID"  NUMBER(10,0),
    "FEATURE_BLOB" VARCHAR2(4000 CHAR),
    "PREVIOUS_GEOMETRY" "MDSYS"."SDO_GEOMETRY" ,
    "CURRENT_GEOMETRY" "MDSYS"."SDO_GEOMETRY" ,
    "PREVIOUS_CONTENT" VARCHAR2(4000 CHAR),
    "CURRENT_CONTENT"  VARCHAR2(4000 CHAR)
  );
  
  CREATE INDEX "IDX_DIFF_OPERATE_LOG" ON "DIFF_OPERATE_LOG"
  (
    "VERSION_ID",
    "OPERATE_ID",
    "INNER_ID"
  );
  
  CREATE TABLE "REGION_CHECK_REPORT"
  (
    "OPERATE_LOG_ID" NVARCHAR2(50),
    "MESH_ID" NVARCHAR2(20),
    "VERSION_ID" NUMBER,
    "TABLE_NAME" NVARCHAR2(50)
  );
  
  
   CREATE TABLE "REGION_CHECK_STAT_REPORT"
  (
    "OPERATE_LOG_ID" NVARCHAR2(50),
    "MESH_ID" NVARCHAR2(20),
    "VERSION_ID" NUMBER,
    "TABLE_NAME" NVARCHAR2(50),
    "DML_TYPE" NVARCHAR2(50)
  );