CREATE OR REPLACE FORCE VIEW "DIFF_OBJECT" ("TABLE_NAME", "OBJECT_NAME", "PID_COLUMN", "TOP_LEVEL", "PARENT_TABLE")
AS
  SELECT "TABLE_NAME",
    "OBJECT_NAME",
    "PID_COLUMN",
    "TOP_LEVEL",
    "PARENT_TABLE"
  FROM diff_object@VM_DB_LINK ;
  
  
CREATE OR REPLACE FORCE VIEW "DIFF_SUITE_COLUMN" ("SUITE_COLUMN_ID", "SUITE_TABLE_ID", "DIFF_COLUMN_ID")
AS
  SELECT "SUITE_COLUMN_ID",
    "SUITE_TABLE_ID",
    "DIFF_COLUMN_ID"
  FROM diff_suite_column@VM_DB_LINK ;
  
  
CREATE OR REPLACE FORCE VIEW "DIFF_SUITE_GROUP" ("SUITE_GROUP_ID", "NAME", "DESCP")
AS
  SELECT "SUITE_GROUP_ID","NAME","DESCP" FROM diff_suite_group@VM_DB_LINK ;
  
  
CREATE OR REPLACE FORCE VIEW "DIFF_SUITE_TABLE" ("SUITE_TABLE_ID", "SUITE_GROUP_ID", "DIFF_TABLE_ID", "DIFF_TYPE")
AS
  SELECT "SUITE_TABLE_ID",
    "SUITE_GROUP_ID",
    "DIFF_TABLE_ID",
    "DIFF_TYPE"
  FROM diff_suite_table@VM_DB_LINK ;
  
CREATE OR REPLACE FORCE VIEW "DIFF_TABLE" ("TABLE_NAME", "TABLE_CNAME")
AS
  SELECT "TABLE_NAME","TABLE_CNAME" FROM diff_table@VM_DB_LINK ;
  
  
CREATE OR REPLACE FORCE VIEW "DIFF_TABLE_COLUMN" ("COLUMN_ID", "TABLE_NAME", "COLUMN_NAME", "DIFF_EXCLUDE", "LOG_EXCLUDE", "DATA_TYPE", "COLUMN_CNAME", "IS_PK", "COL_INDEX")
AS
  SELECT "COLUMN_ID",
    "TABLE_NAME",
    "COLUMN_NAME",
    "DIFF_EXCLUDE",
    "LOG_EXCLUDE",
    "DATA_TYPE",
    "COLUMN_CNAME",
    "IS_PK",
    "COL_INDEX"
  FROM diff_table_column@VM_DB_LINK ;  
  
  
